In [1]:
import numpy as np
import sympy as sym
import scipy as sp

In [2]:
M = np.array([[1, 1, 4], [-1/2, 1, 2]])
sym.Matrix(M).rref()

(Matrix([
 [1, 0, 1.33333333333333],
 [0, 1, 2.66666666666667]]),
 (0, 1))

In [5]:
row = 6
column = 8
rank = 3
A = np.random.randn(row, rank) @ np.random.randn(rank, column)
P, L, U = sp.linalg.lu(A)
P, L, U, np.linalg.matrix_rank(L)

(array([[0., 0., 0., 0., 0., 1.],
        [0., 0., 1., 0., 0., 0.],
        [0., 1., 0., 0., 0., 0.],
        [0., 0., 0., 0., 1., 0.],
        [0., 0., 0., 1., 0., 0.],
        [1., 0., 0., 0., 0., 0.]]),
 array([[ 1.        ,  0.        ,  0.        ,  0.        ,  0.        ,
          0.        ],
        [ 0.88314767,  1.        ,  0.        ,  0.        ,  0.        ,
          0.        ],
        [-0.94728852, -0.64521825,  1.        ,  0.        ,  0.        ,
          0.        ],
        [ 0.23676789,  0.67621436, -0.54027887,  1.        ,  0.        ,
          0.        ],
        [ 0.65787404,  0.96934444, -0.24224941,  0.        ,  1.        ,
          0.        ],
        [-0.40708979, -0.71131091,  0.56423474, -1.        , -0.12121212,
          1.        ]]),
 array([[-1.39768005e+00, -3.87265718e+00,  1.69929568e+00,
         -2.82104351e+00, -3.63927171e-01,  1.45870381e-01,
         -5.61261266e-01,  1.93683467e+00],
        [ 0.00000000e+00,  2.64695398e+00, -5.