In [2]:
import numpy as np

In [3]:
as_array = np.array([1, 2, 3])
row_vec = np.array([[1, 2, 3]])
col_vec = np.array([[1], [2], [3]])
row_vec, col_vec

(array([[1, 2, 3]]),
 array([[1],
        [2],
        [3]]))

In [4]:
row_vec.shape, col_vec.shape

((1, 3), (3, 1))

In [5]:
v = np.array([4, 5, 6])
w = np.array([10, 20, 30])
u = np.array([0, 3, 6, 9])

In [6]:
v + w

array([14, 25, 36])

In [7]:
v = np.array([[4, 5, 6]])
w = np.array([[10, 20, 30]])
wT = w.T

In [8]:
v + wT

array([[14, 15, 16],
       [24, 25, 26],
       [34, 35, 36]])

In [9]:
v = np.array([[1, 2, 3]])
w = np.array([[10, 20]]).T
v + w

array([[11, 12, 13],
       [21, 22, 23]])

In [10]:
(v + w).shape

(2, 3)

In [11]:
v = np.array([1, 2, 3, 7, 8, 9])
np.linalg.norm(v)

14.422205101855956

In [12]:
v = np.array([1, 2, 3])
w = np.array([4, 5, 6])
np.dot(v, w)

32

In [13]:
v = np.array([[1, 2, 3]])
w = np.array([[4, 5, 6]]).T
np.dot(v, w)

array([[32]])

In [14]:
a = np.array([5, 4, 8])
b = np.array([1, 0, 4])
a * b

array([ 5,  0, 32])

In [15]:
v = np.array([[1, 2, 3]]).T
w = np.array([[4, 5, 6]])
np.outer(v, w)

array([[ 4,  5,  6],
       [ 8, 10, 12],
       [12, 15, 18]])

In [18]:
np.sqrt(np.sum(v**2)), np.linalg.norm(v)

(3.7416573867739413, 3.7416573867739413)

In [20]:
v / np.linalg.norm(v)

array([[0.26726124],
       [0.53452248],
       [0.80178373]])

In [26]:
wt = np.zeros((w.shape[1], w.shape[0]))

In [27]:
for i in range(w.shape[1]):
    wt[i, 0] = w[0, i]
wt

array([[4.],
       [5.],
       [6.]])

In [28]:
a = np.array([1, 2])
b = np.array([3, 1])
beta = np.dot(a, b) / np.dot(a, a)
projvect = b - beta*a
projvect

array([ 2., -1.])