In [1]:
import numpy as np

In [12]:
def corr_and_cosine(x, y):
    numerator = np.dot(x, y)
    denominator = np.linalg.norm(x) * np.linalg.norm(y)
    cosine = numerator / denominator

    xm = x - np.mean(x)
    ym = y - np.mean(y)
    numerator_corr = np.dot(xm, ym)
    denominator_corr = np.linalg.norm(xm) * np.linalg.norm(ym)
    correlation = numerator_corr / denominator_corr

    return correlation, cosine

In [13]:
a = np.random.randn(15)
b = np.random.randn(15)
a, b

(array([ 0.80153091, -0.77970427,  2.29721677,  0.38079203,  1.83695197,
         1.15130519,  0.4111353 ,  0.24479019,  1.32734747,  0.60925639,
        -2.62753555,  0.69302472,  1.53337762, -0.58642188, -0.35968319]),
 array([-0.97879906, -2.17262985, -0.75115975,  0.0180867 , -0.68751031,
        -2.0298819 , -0.98028967,  2.2254001 ,  1.25769344, -0.50626987,
        -0.47883235, -1.78144944, -1.47751462, -0.3088788 ,  0.60054823]))

In [14]:
cos, corr = corr_and_cosine(a, b)
cos, corr

(-0.07123015016721505, -0.21344923122637952)

In [15]:
np.corrcoef(a, b)

array([[ 1.        , -0.07123015],
       [-0.07123015,  1.        ]])

In [16]:
import scipy.stats as ss
?? ss.pearsonr

Signature:  ss.pearsonr(x, y, *, alternative='two-sided', method=None)
Source:   
def pearsonr(x, y, *, alternative='two-sided', method=None):
    r"""
    Pearson correlation coefficient and p-value for testing non-correlation.

    The Pearson correlation coefficient [1]_ measures the linear relationship
    between two datasets. Like other correlation
    coefficients, this one varies between -1 and +1 with 0 implying no
    correlation. Correlations of -1 or +1 imply an exact linear relationship.
    Positive correlations imply that as x increases, so does y. Negative
    correlations imply that as x increases, y decreases.

    This function also performs a test of the null hypothesis that the
    distributions underlying the samples are uncorrelated and normally
    distributed. (See Kowalski [3]_
    for a discussion of the effects of non-normality of the input on the
    distribution of the correlation coefficient.)
    The p-value roughly indicates the probability of an uncorr

In [17]:
kernel = np.array([0, .1, .3, .8, 1, .8, .3, .1, 0])
kernel = kernel / np.sum(kernel)
Nkernel = len(kernel)
halfKrn = Nkernel // 2

Nsignal = 100
timeseries = np.random.randn(Nsignal)

filtsig = timeseries.copy()

for t in range(halfKrn+1, Nsignal-halfKrn):
  filtsig[t] = np.dot(kernel, timeseries[t-halfKrn-1:t+halfKrn])

filtsig

array([-1.36161462e+00,  4.86359229e-01,  2.26029831e-01,  5.21451858e-01,
        1.82357527e+00,  7.42972519e-01,  6.69325110e-01,  7.41593211e-01,
        9.53434059e-01,  9.28248582e-01,  5.83039783e-01,  1.39228957e-01,
       -6.46272902e-04, -1.27065944e-01, -1.68955769e-01, -4.10105219e-01,
       -3.84113215e-01, -3.03763747e-01,  1.17739201e-01,  4.90485747e-01,
        5.35736240e-01,  4.06177739e-01,  1.19616138e-01, -2.44631026e-01,
       -7.40883440e-01, -6.98055041e-01, -3.75880243e-01,  6.62866252e-02,
        2.15825999e-01,  5.44039655e-02, -1.47669367e-01, -1.60984657e-01,
        2.74882177e-01,  4.41578750e-01,  3.94920447e-01,  2.45517502e-01,
        3.84737259e-01,  6.60186550e-01,  1.01438969e+00,  1.29254868e+00,
        1.23600732e+00,  1.00366135e+00,  7.88357496e-01,  5.39384630e-01,
        3.08264385e-01,  3.45289240e-02, -2.46935000e-01, -4.52394886e-01,
       -4.62523329e-01, -2.27343098e-01,  2.55886868e-02,  2.35369753e-01,
        3.48140745e-01,  