In [1]:
import numpy as np

In [4]:
# create a symmetric matrix
A = np.random.randn(5,5)
A = A.T@A
# A = A+A.T # uncomment this line to repeat for A+A'

# eigendecomposition
evals,evecs = np.linalg.eig(A)

# sorting them helps the comparison!
sidx  = np.argsort(evals)[::-1]
evals = evals[sidx]
evecs = evecs[:,sidx]



# SVD
U,s,Vt = np.linalg.svd(A)

# compare the eigenvalues and singular values
print('Eigenvalues and singular values:')
print(np.vstack((evals,s)).T)

# now compare the left and right singular vectors
print(f'\nLeft-Right singular vectors (should be zeros)')
print(np.round(U-Vt.T,10)) # remember to compare V not V^T!

# then compare singular vectors with eigenvectors
print(f'\nSingular vectors - eigenvectors (should be zeros)')
print(np.round(U-evecs,10)) # subtract and 
print(' ')                  
print(np.round(U+evecs,10)) # add for sign indeterminancy


Eigenvalues and singular values:
[[11.68233082 11.68233082]
 [10.01536027 10.01536027]
 [ 3.76464987  3.76464987]
 [ 0.74249272  0.74249272]
 [ 0.04650163  0.04650163]]

Left-Right singular vectors (should be zeros)
[[-0.  0. -0.  0. -0.]
 [-0. -0.  0.  0.  0.]
 [-0. -0. -0.  0.  0.]
 [ 0. -0. -0.  0.  0.]
 [-0.  0. -0. -0.  0.]]

Singular vectors - eigenvectors (should be zeros)
[[-0.22231066  0.         -0.         -0.0611909  -0.97988083]
 [ 0.40849189 -0.          0.         -0.39549319 -1.52556086]
 [-1.13229839  0.         -0.          0.09586891 -0.74613346]
 [ 1.53225383 -0.         -0.         -0.32653096 -0.19969644]
 [-0.39218733  0.         -0.         -1.92977395  0.3404465 ]]
 
[[ 0.          1.39903658 -1.0145757   0.          0.        ]
 [-0.         -0.18979687  1.14601952  0.         -0.        ]
 [-0.         -1.25234197 -0.76395939 -0.          0.        ]
 [-0.         -0.66058229 -1.03408322 -0.          0.        ]
 [ 0.          0.04409583 -0.06567602  0.      