In [1]:
import numpy as np

In [4]:
# create an orthogonal matrix, call it U (to avoid confusing with Q)
U = np.linalg.qr( np.random.randn(6,6) )[0]


# part 2: modulate the column norms
for i in range(U.shape[0]):
  U[:,i] = U[:,i]*(10+i)


q, r = np.linalg.qr(U)
print(np.round(q.T @ q, 3))

# part 3: Change one matrix element
U[0,3] = 0 # this is q_{1,4}


# QR decomp
q,r = np.linalg.qr(U)

# show R and, for part 2, Q'Q
print( np.round(r,3) ), print(' ')
# print( np.round(Q.T@Q,4))

[[ 1.  0.  0.  0. -0. -0.]
 [ 0.  1.  0. -0.  0. -0.]
 [ 0.  0.  1.  0. -0.  0.]
 [ 0. -0.  0.  1.  0. -0.]
 [-0.  0. -0.  0.  1. -0.]
 [-0. -0.  0. -0. -0.  1.]]
[[10.     0.    -0.    -1.328  0.     0.   ]
 [ 0.    11.     0.    -0.154  0.     0.   ]
 [ 0.     0.    12.     2.453  0.    -0.   ]
 [ 0.     0.     0.    10.761 -3.916 -5.633]
 [ 0.     0.     0.     0.    13.441 -1.641]
 [ 0.     0.     0.     0.     0.    13.805]]
 


(None, None)

In [12]:
m = 9
A = np.random.randn(m, m)
Q, R = np.linalg.qr(A)
np.linalg.norm(Q, 2), np.sqrt(np.sum(Q**2)), np.linalg.norm(Q, 'fro')

(1.0000000000000002, 2.9999999999999996, 2.9999999999999996)

In [17]:
v = np.random.randn(m, 1)
np.linalg.norm(v), np.linalg.norm(Q @ v), np.linalg.norm(np.dot(Q, v))

(3.1871958444703066, 3.187195844470307, 3.187195844470307)

In [18]:
A = np.random.randn(10, 4)
Q, R = np.linalg.qr(A, 'complete')
R

array([[-3.55323189, -0.75136428,  0.61262235, -0.85000548],
       [ 0.        ,  3.07710885,  1.4073568 , -0.4423664 ],
       [ 0.        ,  0.        ,  2.93591627, -0.23868697],
       [ 0.        ,  0.        ,  0.        ,  1.9659837 ],
       [ 0.        ,  0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  0.        ]])

In [22]:
np.linalg.pinv(R).round(2), np.linalg.inv(R[:4, :]).round(2)

(array([[-0.28, -0.07,  0.09, -0.13,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,
          0.  ],
        [-0.  ,  0.32, -0.16,  0.05,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,
          0.  ],
        [-0.  , -0.  ,  0.34,  0.04,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,
          0.  ],
        [ 0.  , -0.  , -0.  ,  0.51,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,
          0.  ]]),
 array([[-0.28, -0.07,  0.09, -0.13],
        [ 0.  ,  0.32, -0.16,  0.05],
        [ 0.  ,  0.  ,  0.34,  0.04],
        [ 0.  ,  0.  ,  0.  ,  0.51]]))