In [1]:
import numpy as np

In [2]:
A = np.arange(60).reshape(6, 10)
sub = A[1:4, 0:5]
A, sub

(array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
        [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
        [50, 51, 52, 53, 54, 55, 56, 57, 58, 59]]),
 array([[10, 11, 12, 13, 14],
        [20, 21, 22, 23, 24],
        [30, 31, 32, 33, 34]]))

In [3]:
mrows = 4
ncols = 6
A = np.random.randn(mrows, ncols)
A

array([[ 0.48186557, -0.06299354,  1.3425246 ,  0.36227549, -0.38151017,
         1.68543305],
       [-0.16334852,  1.21907217, -0.0028547 ,  0.96207399,  1.57083446,
        -0.58235217],
       [ 0.4789189 ,  0.01186981, -0.6046602 , -0.80032503, -0.30241437,
        -0.57972566],
       [ 0.08157211,  0.19425577, -0.4842434 , -1.98688026,  1.12824559,
         0.92494201]])

In [4]:
A = np.array([[4, 5, 1],
              [0, 1, 11],
              [4, 9, 7]])
s = 6
A + s * np.eye(len(A))

array([[10.,  5.,  1.],
       [ 0.,  7., 11.],
       [ 4.,  9., 13.]])

In [5]:
A = np.random.randn(3, 3)
B = np.random.randn(3, 3)
A * B, A @ B

(array([[ 0.07513871, -0.19293618, -0.859164  ],
        [-5.35375705,  0.14641558, -0.32125828],
        [ 0.7214293 , -1.44026082, -0.31671571]]),
 array([[-1.70731744, -0.89758157,  1.1633162 ],
        [-1.97717876,  0.92926766, -3.50425582],
        [-1.7776522 ,  1.06887363,  1.19343884]]))

In [6]:
A = np.arange(12).reshape(3, 4)
A

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [8]:
row = 2
column = 4
A[row-1, column-1]

7

In [9]:
C = np.arange(100).reshape(10, 10)
C

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [10]:
rows = 5
columns = 5
C[rows-rows:rows, columns-columns:columns]

array([[ 0,  1,  2,  3,  4],
       [10, 11, 12, 13, 14],
       [20, 21, 22, 23, 24],
       [30, 31, 32, 33, 34],
       [40, 41, 42, 43, 44]])

In [13]:
C_1 = C[0:5, 0:5]
C_2 = C[0:5, 5:10]
C_3 = C[5:10, 0:5]
C_4 = C[5:10, 5:10]
np.vstack([(np.hstack([C_4, C_3])), np.hstack([C_2, C_1])])

array([[55, 56, 57, 58, 59, 50, 51, 52, 53, 54],
       [65, 66, 67, 68, 69, 60, 61, 62, 63, 64],
       [75, 76, 77, 78, 79, 70, 71, 72, 73, 74],
       [85, 86, 87, 88, 89, 80, 81, 82, 83, 84],
       [95, 96, 97, 98, 99, 90, 91, 92, 93, 94],
       [ 5,  6,  7,  8,  9,  0,  1,  2,  3,  4],
       [15, 16, 17, 18, 19, 10, 11, 12, 13, 14],
       [25, 26, 27, 28, 29, 20, 21, 22, 23, 24],
       [35, 36, 37, 38, 39, 30, 31, 32, 33, 34],
       [45, 46, 47, 48, 49, 40, 41, 42, 43, 44]])

In [19]:
n = 4
O = np.ones((n, n))
D = np.diag(np.arange(1, n+1)**2)
S = np.sqrt(D)
O, D, S

(array([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]),
 array([[ 1,  0,  0,  0],
        [ 0,  4,  0,  0],
        [ 0,  0,  9,  0],
        [ 0,  0,  0, 16]]),
 array([[1., 0., 0., 0.],
        [0., 2., 0., 0.],
        [0., 0., 3., 0.],
        [0., 0., 0., 4.]]))

In [21]:
D @ O, O @ D

(array([[ 1.,  1.,  1.,  1.],
        [ 4.,  4.,  4.,  4.],
        [ 9.,  9.,  9.,  9.],
        [16., 16., 16., 16.]]),
 array([[ 1.,  4.,  9., 16.],
        [ 1.,  4.,  9., 16.],
        [ 1.,  4.,  9., 16.],
        [ 1.,  4.,  9., 16.]]))

In [22]:
S @ O @ S

array([[ 1.,  2.,  3.,  4.],
       [ 2.,  4.,  6.,  8.],
       [ 3.,  6.,  9., 12.],
       [ 4.,  8., 12., 16.]])