In [1]:
import numpy as np

In [2]:
as_array = np.array([1, 2, 3])
row_vec = np.array([[1, 2, 3]])
col_vec = np.array([[1], [2], [3]])
row_vec, col_vec

(array([[1, 2, 3]]),
 array([[1],
        [2],
        [3]]))

In [3]:
row_vec.shape, col_vec.shape

((1, 3), (3, 1))

In [4]:
v = np.array([4, 5, 6])
w = np.array([10, 20, 30])
u = np.array([0, 3, 6, 9])

In [5]:
v + w

array([14, 25, 36])

In [10]:
v = np.array([[4, 5, 6]])
w = np.array([[10, 20, 30]])
wT = w.T

In [11]:
v + wT

array([[14, 15, 16],
       [24, 25, 26],
       [34, 35, 36]])