In [1]:
import numpy as np

In [2]:
A = np.arange(60).reshape(6, 10)
sub = A[1:4, 0:5]
A, sub

(array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
        [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
        [50, 51, 52, 53, 54, 55, 56, 57, 58, 59]]),
 array([[10, 11, 12, 13, 14],
        [20, 21, 22, 23, 24],
        [30, 31, 32, 33, 34]]))

In [3]:
mrows = 4
ncols = 6
A = np.random.randn(mrows, ncols)
A

array([[ 0.48212363,  1.09244655, -1.17679573,  0.50704667, -0.4307945 ,
        -0.34682924],
       [-0.20395385,  0.01335842, -0.05782874, -0.29041732, -0.22898582,
         1.12625089],
       [ 0.76323993,  0.47002877, -1.25836562, -0.06475671, -0.39891081,
        -0.152359  ],
       [-1.37524448,  0.75679503,  0.682202  ,  0.21827355,  0.10003244,
         1.60153607]])

In [4]:
A = np.array([[4, 5, 1],
              [0, 1, 11],
              [4, 9, 7]])
s = 6
A + s * np.eye(len(A))

array([[10.,  5.,  1.],
       [ 0.,  7., 11.],
       [ 4.,  9., 13.]])

In [6]:
A = np.random.randn(3, 3)
B = np.random.randn(3, 3)
A * B, A @ B

(array([[-0.45956035, -1.35002346, -0.15507799],
        [ 0.20918233, -0.66069919, -2.1613482 ],
        [ 0.63352334,  0.12673277, -0.04044267]]),
 array([[-1.5046749 , -2.46770293, -0.0179345 ],
        [-3.69501379, -0.75527429,  0.75909681],
        [ 1.48455275,  2.06259001,  0.11317587]]))