In [2]:
import numpy as np

In [8]:
k = 4
km = np.arange(1, k+1).reshape(1, -1)
km, 1 / (km.T + km - 1)

(array([[1, 2, 3, 4]]),
 array([[1.        , 0.5       , 0.33333333, 0.25      ],
        [0.5       , 0.33333333, 0.25      , 0.2       ],
        [0.33333333, 0.25      , 0.2       , 0.16666667],
        [0.25      , 0.2       , 0.16666667, 0.14285714]]))

In [11]:
km.T, km, km.T + km - 1

(array([[1],
        [2],
        [3],
        [4]]),
 array([[1, 2, 3, 4]]),
 array([[1, 2, 3, 4],
        [2, 3, 4, 5],
        [3, 4, 5, 6],
        [4, 5, 6, 7]]))

In [12]:
hilbert = 1 / (km.T + km - 1)
hilbert

array([[1.        , 0.5       , 0.33333333, 0.25      ],
       [0.5       , 0.33333333, 0.25      , 0.2       ],
       [0.33333333, 0.25      , 0.2       , 0.16666667],
       [0.25      , 0.2       , 0.16666667, 0.14285714]])

In [13]:
hilbert @ np.linalg.inv(hilbert)

array([[ 1.00000000e+00,  0.00000000e+00,  2.27373675e-13,
         0.00000000e+00],
       [-1.55431223e-15,  1.00000000e+00,  1.12532206e-13,
         3.10862447e-14],
       [ 1.29526020e-15, -3.44909286e-14,  1.00000000e+00,
        -4.48530102e-14],
       [-5.99520433e-15,  8.00629404e-14, -1.61585031e-13,
         1.00000000e+00]])

In [14]:
np.linalg.cond(hilbert)

15513.73873892924