In [1]:
import numpy as np
import sympy as sp

In [2]:
a = np.array([[1, 2, -1], [3, 1, 0]])
b = np.array([[-2, 1], [0, -3], [2, 1]])
np.dot(a, b)

array([[-4, -6],
       [-6,  0]])

In [3]:
a = np.array([[1, 0, 0],
[0, 1, 0],
[-2, 0, 1]])
b = np.array([[1, 0, 0],
[0, 1, 0],
[2, 0, 1]])
np.dot(a, b)

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [4]:
a = np.array([[4, 3], [6, 5]])
np.linalg.det(a)

1.999999999999998

In [5]:
a = np.array([[1, 1, 1, 1], [1, 2, 4, 8], [1, 3, 9, 27], [1, 4, 16, 64]])
b = np.array([[3, -2, -5, 0]]).reshape(-1, 1)
np.dot(np.linalg.inv(a), b)

array([[ 4.],
       [ 3.],
       [-5.],
       [ 1.]])

In [6]:
a = np.array([[3, 7, 1], [-2, 1, 1], [5, -2, 1]])
np.linalg.det(a)

57.00000000000001

In [7]:
a = np.array([[-1, 2, 3, -1]]).reshape(-1, 1)
b = np.array([[2, 1, 0, 2]]).reshape(-1, 1)
inner_product = 0
for comp in zip(a, b):
    inner_product += comp[0] * comp[1]
int(inner_product)

-2

In [8]:
t1 = np.array([1, 1]).reshape(-1, 1)
t2 = np.array([1, -1]).reshape(-1, 1)
t = np.hstack([t1, t2])
x = np.array([5, -2]).reshape(-1, 1)
y = np.array([3, 4]).reshape(-1, 1)
np.dot(np.linalg.inv(t), x), np.dot(np.linalg.inv(t), y), np.dot(np.linalg.inv(t), x + y)

(array([[1.5],
        [3.5]]),
 array([[ 3.5],
        [-0.5]]),
 array([[5.],
        [3.]]))

In [9]:
A = np.array([[1, 1, 2], [3, 4, 1], [3, 7, 1], [4, 2, 3]])
b = np.array([11, 2, -7, 21]).reshape(-1, 1)
np.dot(np.dot(np.linalg.inv(np.dot(A.transpose(), A)), A.transpose()), b)

array([[ 2.51428571],
       [-2.85714286],
       [ 5.6       ]])

In [10]:
a = np.array([[1, 2, 2], [1, 2, -1], [3, -3, 0]])
np.linalg.det(a)

-27.0

In [11]:
a = np.array([[4, 1], [5, 1]])
np.linalg.det(a)

-0.9999999999999998

In [12]:
a = np.array([[1, 1, 1, 0], [1, 1, 0, 1], [1, 1, 2, -1]]).transpose()

In [13]:
a = np.array([[2, 0, 0], [4, 1, 1], [-3, 1, -1]])
np.linalg.inv(a)

array([[ 0.5 ,  0.  ,  0.  ],
       [-0.25,  0.5 ,  0.5 ],
       [-1.75,  0.5 , -0.5 ]])

In [14]:
a = sp.Matrix([[-1, 2, 0, 4, 5, -3], [3, -7, 2, 0, 1, 4], [2, -5, 2, 4, 6, 1], [4, -9, 2, -4, -4, 7]])
a.rref()

(Matrix([
 [1, 0, -4, -28, -37, 13],
 [0, 1, -2, -12, -16,  5],
 [0, 0,  0,   0,   0,  0],
 [0, 0,  0,   0,   0,  0]]),
 (0, 1))

In [15]:
x = np.array([[2, 3, 1]]).reshape(-1, 1)
S = np.array([[1, 1, 0], [1, 1, 1], [0, 1, -1]])
S_inv = np.linalg.inv(S)
np.dot(S_inv, x)

array([[0.],
       [2.],
       [1.]])

In [16]:
A_and_T = sp.Matrix([[1, 1, 2, 4, 5, 6], [2, 1, 0, -1, 5, 3], [0, 1, 1, 3, 2, 3]])
A_and_T.rref()

(Matrix([
 [1, 0, 0, -1, 2, 1],
 [0, 1, 0,  1, 1, 1],
 [0, 0, 1,  2, 1, 2]]),
 (0, 1, 2))

In [17]:
A = np.array([[35, 42, 77], [42, 70, 112], [77, 112, 189]])
np.linalg.det(A)

9.748646334628575e-12

In [18]:
A = np.array([[3, 2], [3, 2]])
A_T = A.transpose()
b = np.array([[12, 6]]).reshape(-1, 1)
try:
    np.linalg.inv(np.dot(A_T, A))
except:
    print('역행렬이 없음', np.linalg.det(np.dot(A_T, A)))
#A_T_multiple_A_inv = np.linalg.inv(np.dot(A_T, A))
#x = np.dot(A_T_multiple_A_inv, A_T, b)

역행렬이 없음 0.0


In [19]:
A = sp.Matrix([[1, 3, -2, 0, 2, 0, 0], [2, 6, -5, -2, 4, -3, -1],
[0, 0, 5, 10, 0, 15, 5], [2, 6, 0, 8, 4, 18, 6]])
A.rref()


(Matrix([
 [1, 3, 0, 4, 2, 0,   0],
 [0, 0, 1, 2, 0, 0,   0],
 [0, 0, 0, 0, 0, 1, 1/3],
 [0, 0, 0, 0, 0, 0,   0]]),
 (0, 2, 5))

In [20]:
A = np.array([[2, -3, 0], [1, 3, 0]])
B = np.array([[2, -1, 0], [6, -3, 0]])
A = sp.Matrix(A)
B = sp.Matrix(B)
A.rref(), B.rref()

((Matrix([
  [1, 0, 0],
  [0, 1, 0]]),
  (0, 1)),
 (Matrix([
  [1, -1/2, 0],
  [0,    0, 0]]),
  (0,)))

In [21]:
A = np.array([[2, -3], [1, 3]])
B = np.array([[2, -1], [6, -3]])
np.linalg.det(A), np.linalg.det(B)

(9.000000000000002, 0.0)

In [22]:
A = np.array([[-2, 7, 3], [1, 5, 8], [0, 0, 0]])
np.linalg.det(A)

0.0

In [23]:
A = np.array([[1, 2, 3, 1, 0, 0], [2, 5, 3, 0, 1, 0], [1, 0, 8, 0, 0, 1]])
A_sp = sp.Matrix(A)
A_sp.rref()

(Matrix([
 [1, 0, 0, -40, 16,  9],
 [0, 1, 0,  13, -5, -3],
 [0, 0, 1,   5, -2, -1]]),
 (0, 1, 2))

In [24]:
A = np.array([[1, 2, 3], [2, 5, 3], [1, 0, 8]])
b = np.array([[1, 3, -1]]).transpose()
np.dot(np.linalg.inv(A), b).round(2)

array([[-1.],
       [ 1.],
       [-0.]])

In [25]:
A = np.array([[0, 0, 0, 1, 10], [1, 1, 1, 1, 7], [27, 9, 3, 1, -11], [64, 16, 4, 1, -14]])
A_sp = sp.Matrix(A)
A_sp.rref()

(Matrix([
 [1, 0, 0, 0,  1],
 [0, 1, 0, 0, -6],
 [0, 0, 1, 0,  2],
 [0, 0, 0, 1, 10]]),
 (0, 1, 2, 3))

In [26]:
A = np.array([[1, 2, 1], [1, 1, 0], [2, -1, 1]])
A_3 = 3 * A
np.linalg.det(A), np.linalg.det(A_3), 27 * 4

(-4.000000000000001, -108.00000000000003, 108)

In [27]:
A = np.array([[2, -3, 1], [4, 2, 2], [1, 0, -2]])
A_sp = sp.Matrix(A)
adj_A = np.array(A_sp.adjugate())
np.dot(A, adj_A)
np.dot((1 / np.linalg.det(A)), adj_A)

array([[0.100000000000000, 0.150000000000000, 0.200000000000000],
       [-0.250000000000000, 0.125000000000000, 0],
       [0.0500000000000000, 0.0750000000000000, -0.400000000000000]],
      dtype=object)

In [28]:
A = np.array([[3, 2, 4], [2, -1, 1], [1, 2, 3]])
b = np.array([[1, 0, 1]]).transpose()
det_A = np.linalg.det(A).round(0)
A[:, 0] = b.transpose()
det_b1 = np.linalg.det(A)
x1 = det_b1 / det_A
x1

-0.2

In [29]:
V = np.array([[1, 1, 1, 1], [1, 2, 4, 8], [1, 3, 9, 27], [1, 4, 16, 64]])
p_x = np.array([[3, -2, -5, 0]]).transpose()
np.dot(np.linalg.inv(V), p_x)

array([[ 4.],
       [ 3.],
       [-5.],
       [ 1.]])

In [30]:
V = np.array([[1, 0, 0, 0], [1, 1, 1, 1], [1, 3, 9, 27], [1, 4, 16, 64]])
b = np.array([[10, 7, -11, -14]]).transpose()
np.dot(np.linalg.inv(V), b)

array([[10.],
       [ 2.],
       [-6.],
       [ 1.]])

In [31]:
v = np.array([[-2, 7]])
np.linalg.norm(v)

7.280109889280518

In [32]:
u = np.array([[0, 2, -1]])
v = np.array([[-1, 1, 2]])
np.dot(u, v.transpose())

array([[0]])

In [33]:
norm_u = np.linalg.norm(u)
norm_v = np.linalg.norm(v)
norm_u * norm_v

5.477225575051661

In [34]:
x = np.array([[-3, -2, 2]])
y = np.array([[-2, 2, 3]])
np.cross(x, y)
np.linalg.norm(np.cross(x, y))

15.0

In [35]:
x = np.array([[1, 3, -4, 1, -4]])
y = np.array([[2, -1, 2, -2, 0]])
np.dot(x, y.transpose())
np.linalg.norm(x) * np.linalg.norm(y)
np.linalg.norm(x + y)

5.830951894845301

In [36]:
x = np.array([[2, 0, 1, -1]])
y = np.array([[-3, 2, 3, -3]])
np.dot(x, y.transpose())[0][0]

0

In [37]:
np.dot(y.transpose(), x)

array([[-6,  0, -3,  3],
       [ 4,  0,  2, -2],
       [ 6,  0,  3, -3],
       [-6,  0, -3,  3]])

In [38]:
S = np.array([[1, 3, 1, -2, -3], [1, 4, 3, -1, -4], [2, 3, -4, -7, -3], [3, 8, 1, -7, -8]])
S_sp = sp.Matrix(S)
S_sp.rref()

(Matrix([
 [1, 0, -5, -5,  0],
 [0, 1,  2,  1, -1],
 [0, 0,  0,  0,  0],
 [0, 0,  0,  0,  0]]),
 (0, 1))

In [39]:
S = np.array([[0, 1, 0], [3, 0, 1]])
S_sp = sp.Matrix(S)
S_sp.rref()

(Matrix([
 [1, 0, 1/3],
 [0, 1,   0]]),
 (0, 1))

In [40]:
S = np.array([[2, 4, -3], [0, 1, 1], [0, 1, -1]])
S_sp = sp.Matrix(S)
S_sp.rref()

(Matrix([
 [1, 0, 0],
 [0, 1, 0],
 [0, 0, 1]]),
 (0, 1, 2))

In [41]:
S = np.array([[1, 2, 3, 9], [2, -1, 1, 8], [3, 0, -1, 3]])
S_sp = sp.Matrix(S)
S_sp.rref()

(Matrix([
 [1, 0, 0,  2],
 [0, 1, 0, -1],
 [0, 0, 1,  3]]),
 (0, 1, 2))

In [42]:
S = np.array([[-1, 2, 0, 4, 5, -3], [3, -7, 2, 0, 1, 4], [2, -5, 2, 4, 6, 1], [4, -9, 2, -4, -4, 7]])
S_sp = sp.Matrix(S)
S_sp.rref()

(Matrix([
 [1, 0, -4, -28, -37, 13],
 [0, 1, -2, -12, -16,  5],
 [0, 0,  0,   0,   0,  0],
 [0, 0,  0,   0,   0,  0]]),
 (0, 1))

In [43]:
S = np.array([[1, 1, 0], [1, 1, 1], [0, 1, -1]]).transpose()
x = np.array([[2, 3, 1]]).transpose()
x_s = np.dot(np.linalg.inv(S), x)
x_s

array([[0.],
       [2.],
       [1.]])

In [44]:
S = np.array([[1, 0], [0, 1]]).transpose()
x = np.array([[5, -2]]).transpose()
x_s = np.dot(np.linalg.inv(S), x)
x_s

array([[ 5.],
       [-2.]])

In [45]:
S = np.array([[1, 1], [1, -1]]).transpose()
x = np.array([[5, -2]]).transpose()
x_s = np.dot(np.linalg.inv(S), x)
x_s

array([[1.5],
       [3.5]])

In [46]:
S = np.array([[1, 1, 2], [2, 1, 0], [0, 1, 1]])
y1 = np.array([[4, -1, 3]]).transpose()
y2 = np.array([[5, 5, 2]]).transpose()
y3 = np.array([[6, 3, 3]]).transpose()
y1_s = np.dot(np.linalg.inv(S), y1)
y2_s = np.dot(np.linalg.inv(S), y2)
y3_s = np.dot(np.linalg.inv(S), y3)
P = np.hstack([y1_s, y2_s, y3_s])
P

array([[-1.,  2.,  1.],
       [ 1.,  1.,  1.],
       [ 2.,  1.,  2.]])

In [47]:
y = np.array([[2, 1, 1]]).transpose()
x1 = np.array([[0, 1, 0]]).transpose()
x2 = np.array([[0.6, 0, -0.8]]).transpose()
np.dot(x1.transpose(), y)[0][0] * x1 + np.dot(x2.transpose(), y)[0][0] * x2

array([[ 0.24],
       [ 1.  ],
       [-0.32]])

In [48]:
A = np.array([[1, -1], [3, 2], [-2, 4]])
b = np.array([[4, 1, 3]]).transpose()
ATA = np.dot(A.transpose(), A)
ATb = np.dot(A.transpose(), b)
x = np.dot(np.linalg.inv(ATA), ATb)
np.linalg.norm(b - np.dot(A, x))

4.561086358745012

In [49]:
A = np.array([[1, 3, 3, 4], [1, 4, 7, 2], [2, 7, 10, 6]])
A_sp = sp.Matrix(A)
A_sp.rref()

(Matrix([
 [1, 0, -9, 10],
 [0, 1,  4, -2],
 [0, 0,  0,  0]]),
 (0, 1))

In [50]:
A = np.array([[1, 1, 1, 0], [1, 1, 0, 1], [1, 1, 2, -1]]).transpose()
A_sp = sp.Matrix(A)
A_sp.rref()

(Matrix([
 [1, 0,  2],
 [0, 1, -1],
 [0, 0,  0],
 [0, 0,  0]]),
 (0, 1))

In [51]:
A = np.array([[1, 0, 1], [1, 1, 2], [2, 1, 3]])
A_sp = sp.Matrix(A)
A_sp.rref()

(Matrix([
 [1, 0, 1],
 [0, 1, 1],
 [0, 0, 0]]),
 (0, 1))

In [52]:
A = np.array([[1, 1, 2, 3], [3, 4, 3, 8], [1, 3, -4, 1], [-2, -1, -7, -7], [-3, -4, -3, -8]])
A_sp = sp.Matrix(A)
A_sp.rref()

(Matrix([
 [1, 0,  5,  4],
 [0, 1, -3, -1],
 [0, 0,  0,  0],
 [0, 0,  0,  0],
 [0, 0,  0,  0]]),
 (0, 1))

In [53]:
A = np.array([[1, 2, 0], [0, 1, 1]])
A_sp = sp.Matrix(A)
A_sp.rref()

(Matrix([
 [1, 0, -2],
 [0, 1,  1]]),
 (0, 1))

In [54]:
A = np.array([[6, -3], [-1, 1]])
B = np.array([[1/3, 1], [1/3, 2]])
np.dot(B, A)

array([[1., 0.],
       [0., 1.]])

In [55]:
B = np.array([[1/3, 1], [1/3, 2]])
x = np.array([-18, 5]).transpose()
np.dot(B, x)

array([-1.,  4.])

In [56]:
T = np.array([[1, -1], [1, 1]])
S = np.array([[1, 0, 1], [0, 1, 1], [1, 1, 0]])
x1 = S[:, 0].reshape(-1, 1)
x2 = S[:, 1].reshape(-1, 1)
x3 = S[:, 2].reshape(-1, 1)
A_e = np.array([[1, -1, 0], [0, 1, -1]])
Lx1 = np.dot(A_e, x1)
Lx2 = np.dot(A_e, x2)
Lx3 = np.dot(A_e, x3)
L_x1_T = np.dot(np.linalg.inv(T), Lx1)
L_x2_T = np.dot(np.linalg.inv(T), Lx2)
L_x3_T = np.dot(np.linalg.inv(T), Lx3)
np.hstack([L_x1_T, L_x2_T, L_x3_T])

array([[ 0. , -0.5,  0.5],
       [-1. ,  0.5,  0.5]])

In [57]:
A = np.array([[1, -1], [1, 1]])
S = np.array([[1, 0], [0, 1]])
T = np.array([[0, -1], [1, 1]])
P = np.dot(np.linalg.inv(S), T)
P_inv = np.dot(np.linalg.inv(T), S)
P, P_inv
np.dot(np.dot(P_inv, A), P)



array([[ 0., -2.],
       [ 1.,  2.]])

In [58]:
A = np.array([[1, 2, 2, 1, 2, -1, 3, -3, 0]]).reshape(3, -3)
np.linalg.eig(A)

(array([ 3., -3.,  3.]),
 array([[ 0.78446454,  0.53452248, -0.19587907],
        [ 0.19611614, -0.26726124, -0.78439677],
        [ 0.58834841, -0.80178373,  0.58851771]]))

In [59]:
I = np.identity(3)
sp.Matrix(3 * I - A).rref()

(Matrix([
 [1, -1.0, -1.0],
 [0,    0,    0],
 [0,    0,    0]]),
 (0,))

In [60]:
A = np.array([[7, -4, 5, -2]]).reshape(2, -2)
np.linalg.eig(A)

(array([3., 2.]),
 array([[0.70710678, 0.62469505],
        [0.70710678, 0.78086881]]))

In [61]:
I = np.identity(2)
sp.Matrix(3 * I - A).rref()
sp.Matrix(2 * I - A).rref()

(Matrix([
 [1, -0.8],
 [0,    0]]),
 (0,))

In [62]:
A = np.array([[1, 1, 0, 1, 0, 1, -2, 1, 3]]).reshape(-3, 3)
sp.Matrix(A).rref()

(Matrix([
 [1, 0, 0],
 [0, 1, 0],
 [0, 0, 1]]),
 (0, 1, 2))

In [63]:
A = np.array([[4, -2, 1, 2, 0, 1, 2, -2, 3]]).reshape(3, -3)
B = np.array([[0, 0, 1, 0, 1, 2, 0, 0, 1]]).reshape(3, -3)
I = np.identity(3)
np.linalg.eig(A), np.linalg.eig(B)

((array([3., 2., 2.]),
  array([[ 0.57735027,  0.43624197,  0.65716998],
         [ 0.57735027,  0.71160833,  0.31472427],
         [ 0.57735027,  0.55073272, -0.68489142]])),
 (array([0., 1., 1.]),
  array([[ 1.00000000e+00,  0.00000000e+00,  1.11022302e-16],
         [ 0.00000000e+00,  1.00000000e+00, -1.00000000e+00],
         [ 0.00000000e+00,  0.00000000e+00,  1.11022302e-16]])))

In [64]:
sp.Matrix(2 * I - A).rref()

(Matrix([
 [1, -1.0, 0.5],
 [0,    0,   0],
 [0,    0,   0]]),
 (0,))

In [65]:
P = np.array([[0, -1, 2, 1, 0, 0, 0, 2, 1]]).reshape(3, -3)
A = np.array([[0, 0, -2, 0, -2, 0, -2, 0, 3]]).reshape(3, -3)
np.dot(np.dot(P.transpose(), A), P)

array([[-2,  0,  0],
       [ 0, 20,  0],
       [ 0,  0, -5]])

In [66]:
A = np.array([[4, 11, 14, 8, 7, -2]]).reshape(-2, 3)
np.linalg.svd(A)

(array([[ 0.9486833 , -0.31622777],
        [ 0.31622777,  0.9486833 ]]),
 array([18.97366596,  9.48683298]),
 array([[ 0.33333333,  0.66666667,  0.66666667],
        [ 0.66666667,  0.33333333, -0.66666667],
        [-0.66666667,  0.66666667, -0.33333333]]))

In [67]:
A = np.array([[1, -1, -2, 2, 2, -2]]).reshape(-3, 2)
np.linalg.svd(A)

(array([[-0.33333333,  0.66666667, -0.66666667],
        [ 0.66666667,  0.66666667,  0.33333333],
        [-0.66666667,  0.33333333,  0.66666667]]),
 array([4.24264069, 0.        ]),
 array([[-0.70710678,  0.70710678],
        [ 0.70710678,  0.70710678]]))

In [68]:
eigenvalue, eigenvector = np.linalg.eig(np.dot(A.transpose(), A))
for ev in eigenvalue:
    print(sp.Matrix(ev * np.identity(2) - np.dot(A.transpose(), A)).rref())

(Matrix([
[1, 1.0],
[0,   0]]), (0,))
(Matrix([
[1, -1.0],
[0,    0]]), (0,))


In [69]:
A = np.array([[1, -1, 1, 1]]).reshape(2, -2)
np.linalg.eig(A)

(array([1.+1.j, 1.-1.j]),
 array([[0.70710678+0.j        , 0.70710678-0.j        ],
        [0.        -0.70710678j, 0.        +0.70710678j]]))

In [70]:
A = np.array([[3, 0, 0, -4, 6, 2, 16, -15, -5]]).reshape(3, 3)
sp.Matrix(np.identity(3) - A).rref()

(Matrix([
 [1, 0,   0],
 [0, 1, 0.4],
 [0, 0,   0]]),
 (0, 1))

In [71]:
A = np.array([[0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0]]).reshape(5, 5)
np.linalg.eig(A)

(array([ 1.65930207+0.j        , -0.47101902+1.22767294j,
        -0.47101902-1.22767294j, -0.35863201+0.46897406j,
        -0.35863201-0.46897406j]),
 array([[ 0.60571766+0.j        , -0.02485126+0.50859463j,
         -0.02485126-0.50859463j, -0.46352816+0.04455464j,
         -0.46352816-0.04455464j],
        [ 0.55368192+0.j        , -0.18784717-0.07458128j,
         -0.18784717+0.07458128j, -0.22191424-0.5019018j ,
         -0.22191424+0.5019018j ],
        [ 0.46733891+0.j        ,  0.60487629+0.j        ,
          0.60487629-0.j        , -0.05229083-0.19261437j,
         -0.05229083+0.19261437j],
        [ 0.16973876+0.j        , -0.26005698+0.23399562j,
         -0.26005698-0.23399562j,  0.57261247+0.j        ,
          0.57261247-0.j        ],
        [ 0.28164788+0.j        , -0.1647783 -0.4294813j ,
         -0.1647783 +0.4294813j , -0.20535716+0.2685404j ,
         -0.20535716-0.2685404j ]]))

In [72]:
A = np.array([[1, 1, 1, -1]]).reshape(2, 2)
sp.Matrix(A).rref()

(Matrix([
 [1, 0],
 [0, 1]]),
 (0, 1))

In [73]:
T = np.array([[1, -1, 0, 0, 2, 1, -1, 1, 1]]).reshape(3, 3)
Lx1 = np.array([[1, -1, -2]]).transpose()
Lx2 = np.array([[2, 1, -5]]).transpose()
Lx = np.hstack([Lx1, Lx2])
np.dot(np.linalg.inv(T), Lx)

array([[ 1.,  4.],
       [ 0.,  2.],
       [-1., -3.]])

In [74]:
A = np.array([[1, -1, -2, 2, 2, -2]]).reshape(3, 2)
A
np.linalg.svd(A)

(array([[-0.33333333,  0.66666667, -0.66666667],
        [ 0.66666667,  0.66666667,  0.33333333],
        [-0.66666667,  0.33333333,  0.66666667]]),
 array([4.24264069, 0.        ]),
 array([[-0.70710678,  0.70710678],
        [ 0.70710678,  0.70710678]]))

In [75]:
np.dot(A.transpose(), A)

array([[ 9, -9],
       [-9,  9]])

In [76]:
A = np.array([[1, 2, 3, 1, 0, 0, 2, 5, 3, 0, 1, 0, 1, 0, 8, 0, 0, 1]]).reshape(-1, 6)
sp.Matrix(A).rref()

(Matrix([
 [1, 0, 0, -40, 16,  9],
 [0, 1, 0,  13, -5, -3],
 [0, 0, 1,   5, -2, -1]]),
 (0, 1, 2))

In [77]:
V = np.array([[1, 0, 0, 0, 1, 1, 1, 1, 1, 3, 9, 27, 1, 4, 16, 64]]).reshape(4, 4)
b= np.array([[10, 7, -11, -14]]).T
np.dot(np.linalg.inv(V), b)

array([[10.],
       [ 2.],
       [-6.],
       [ 1.]])

In [78]:
A = np.array([[0, 0, 0, 1, 10], [1, 1, 1, 1, 7], [27, 9, 3, 1, -11], [64, 16, 4, 1, -14]])
A_sp = sp.Matrix(A)
A_sp.rref()

(Matrix([
 [1, 0, 0, 0,  1],
 [0, 1, 0, 0, -6],
 [0, 0, 1, 0,  2],
 [0, 0, 0, 1, 10]]),
 (0, 1, 2, 3))

In [79]:
x = np.array([[2, 1, -3]])
y = np.array([[4, 1, 1]])
z = np.array([[-2, 0, 2]])
np.dot(x, np.cross(y, z).T)

array([[-12]])

In [80]:
X = np.array([[1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 2, -1]]).reshape(3, 4).T
sp.Matrix(X).rref()

(Matrix([
 [1, 0,  2],
 [0, 1, -1],
 [0, 0,  0],
 [0, 0,  0]]),
 (0, 1))

In [81]:
A = np.array([[3, 0, 0, -4, 6, 2, 16, -15, -5]]).reshape(3, 3)
sp.Matrix(A).rref()

(Matrix([
 [1, 0,   0],
 [0, 1, 1/3],
 [0, 0,   0]]),
 (0, 1))

In [82]:
P = np.array([[4, 1, 5, 1]]).reshape(2, 2)
A = np.array([[7, -4, 5, -2]]).reshape(2, 2)
np.dot(np.dot(np.linalg.inv(P), A), P).round(0)

array([[ 2., -0.],
       [ 0.,  3.]])

In [85]:
A = np.array([[1, -1, 0, 0, 1, -1]]).reshape(2, 3)
S = np.array([[1, 0, 1, 0, 1, 1, 1, 1, 0]]).reshape(3, 3)
T = np.array([[1, -1, 1, 1]]).reshape(2, 2)
np.dot(np.linalg.inv(T), np.dot(A, S))

array([[ 0. , -0.5,  0.5],
       [-1. ,  0.5,  0.5]])

In [89]:
V = np.array([[0, 2, 3, 2, 0, 0, 0, 1, 2, 2]]).reshape(2, 5)
T = np.array([[0, -1, 1, 0]]).reshape(2, 2)
V_T = np.dot(T, V)
parellel =np.array([[1, 0, 3, 0, 1, 2, 0, 0, 1]]).reshape(3, 3)
homo_coords = np.vstack([V_T, [1, 1, 1, 1, 1]])
np.dot(parellel, homo_coords)

array([[3, 3, 2, 1, 1],
       [2, 4, 5, 4, 2],
       [1, 1, 1, 1, 1]])