In [1]:
import numpy as np
import sympy as sp

In [2]:
A = sp.Matrix([[0, 2, -7, -17],
               [2, 2, 4, 18],
               [3, 6, -5, 0]])
A.rref()

(Matrix([
 [1, 0, 0, 1],
 [0, 1, 0, 2],
 [0, 0, 1, 3]]),
 (0, 1, 2))

In [3]:
A = sp.Matrix([[1, 3, -2, 0, 2, 0, 0],
               [2, 6, -5, -2, 4, -3, -1],
               [0, 0, 5, 10, 0, 15, 5],
               [2, 6, 0, 8, 4, 18, 6]])
A.rref()

(Matrix([
 [1, 3, 0, 4, 2, 0,   0],
 [0, 0, 1, 2, 0, 0,   0],
 [0, 0, 0, 0, 0, 1, 1/3],
 [0, 0, 0, 0, 0, 0,   0]]),
 (0, 2, 5))

In [4]:
a = np.array([[1, 2, -1], [3, 1, 0]])
b = np.array([[-2, 1], [0, -3], [2, 1]])
np.dot(a, b)

array([[-4, -6],
       [-6,  0]])

In [5]:
a = np.array([[1, 2, -1],
              [3, 1, 0]])
b = np.array([[-2, 1],
              [0, -3],
              [2, 1]])
np.dot(b, a)

array([[ 1, -3,  2],
       [-9, -3,  0],
       [ 5,  5, -2]])

In [6]:
a = np.array([[-2, -5],
              [-1, -3]])
b = np.array([[-3, 5],
              [1, -2]])
np.dot(b, a)

array([[1, 0],
       [0, 1]])

In [7]:
np.linalg.inv(a)

array([[-3.,  5.],
       [ 1., -2.]])

In [8]:
A = sp.Matrix([[1, 6, 4, 1, 0, 0],
               [2, 4, -1, 0, 1, 0],
               [-1, 2, 5, 0, 0, 1]])
A.rref()

(Matrix([
 [1, 0, -11/4, 0, 1/4, -1/2],
 [0, 1,   9/8, 0, 1/8,  1/4],
 [0, 0,     0, 1,  -1,   -1]]),
 (0, 1, 3))

In [9]:
a = np.array([[1, 2, 3],
              [2, 5, 3],
              [1, 0, 8]])
b = np.array([[1],
              [3],
              [-1]])
np.dot(np.linalg.inv(a), b)

array([[-1.],
       [ 1.],
       [ 0.]])

In [10]:
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [11]:
A = np.array([[0, 1, 5],
              [3, -6, 9],
              [2, 6, 1]])
np.linalg.det(A)

165.00000000000009

In [12]:
A = np.array([[2, -3, 1],
              [4, 2, 2],
              [1, 0, -2]])
A_sp = sp.Matrix(A)
np.array(A_sp.adjugate())

array([[-4, -6, -8],
       [10, -5, 0],
       [-2, -3, 16]], dtype=object)

In [13]:
A = np.array([[3, 2, 4],
              [2, -1, 1],
              [1, 2, 3]])
b = np.array([[1],
              [0],
              [1]])
det_A = round(np.linalg.det(A))
A[:, [2]] = b
det_M2 = round(np.linalg.det(A))
det_A, det_M2, det_M2 / det_A


(-5, -2, 0.4)

In [14]:
A = np.array([[1, -2],
              [1, 5]])
b = np.array([[1],
              [-2]])
np.dot(np.linalg.inv(A), b)

array([[ 0.14285714],
       [-0.42857143]])

In [15]:
A = np.array([1, 2, -2])
B = np.array([3, 0, 1])
np.dot(A, B), np.cross(A, B)

(1, array([ 2, -7, -6]))

In [16]:
A = np.array([3, 0, 1])
B = np.array([1, 2, -2])
C = np.array([2, 0, -1])
np.cross(A, (B + C))

array([-2, 12,  6])

In [17]:
P = np.array([2, 2, 0])
Q = np.array([-1, 0, 2])
R = np.array([0, 4, 3])
PQ = Q - P
PR = R - P
np.linalg.norm(np.cross(PQ, PR))

15.0

In [18]:
A = np.array([2, 1, -3])
B = np.array([4, 1, 1])
C = np.array([-2, 0, 2])
np.linalg.det(np.vstack([A, B, C]))

-12.0

In [19]:
X = np.array([1, 3, -4, 1, -3])
Y = np.array([2, -1, 2, -2, 0])
(1 / np.linalg.norm(X)) * X

array([ 0.16666667,  0.5       , -0.66666667,  0.16666667, -0.5       ])

In [20]:
X = np.array([2, 0, 1, -1])
Y = np.array([-3, 2, 3, -3])
np.dot(X, Y)

0

In [21]:
P = np.array([1, 2, 0])
Q = np.array([5, -1, 2])
PQ = Q - P
PQ

array([ 4, -3,  2])

In [22]:
X = np.array([2, -1, 3])
Y = np.array([4, -1, 2])
X_dot_Y = np.dot(X, Y)
Y_norm = np.linalg.norm(Y)
(X_dot_Y / (Y_norm * Y_norm)) * Y

array([ 2.85714286, -0.71428571,  1.42857143])

In [23]:
A = np.array([[1, 1, 2],
              [1, 2, -1],
              [1, 3, 1]])
B = np.array([1, -2, 5]).reshape(-1, 1)
np.dot(np.linalg.inv(A), B)

array([[-6.],
       [ 3.],
       [ 2.]])

In [24]:
A = np.array([[2, 1, 0],
              [1, -1, 3],
              [0, 2, -4]])
np.linalg.det(A)

0.0

In [25]:
A = np.array([[1, 1, 5],
              [-1, 3, 3],
              [0, -1, -2]])
np.linalg.det(A)

0.0

In [26]:
S = np.array([[1, 1, 0],
              [1, 1, 1],
              [0, 1, -1]])
x = np.array([2, 3, 1]).reshape(-1, 1)
np.dot(np.linalg.inv(S), x)

array([[0.],
       [2.],
       [1.]])

In [27]:
S = np.array([[1, 1, 2],
              [2, 1, 0],
              [0, 1, 1]])
T = np.array([[4, 5, 6],
              [-1, 5, 3],
              [3, 2, 3]])
P = np.dot(np.linalg.inv(S), T)
Q = np.linalg.inv(P).round(3)
Q

array([[-0.5,  1.5, -0.5],
       [-0. ,  2. , -1. ],
       [ 0.5, -2.5,  1.5]])

In [28]:
X_s = np.array([1, -1, 1]).reshape(-1, 1)
X = np.dot(S, X_s)
np.dot(np.linalg.inv(T), X)

array([[-2.5],
       [-3. ],
       [ 4.5]])

In [29]:
A = np.array([[6, -3],
              [-1, 1]])
A_inv = np.linalg.inv(A)
b1 = np.array([-18, 5]).reshape(-1, 1)
b2 = np.array([15, -2]).reshape(-1, 1)
b3 = np.array([-6, 4]).reshape(-1, 1)
np.dot(A_inv, b1), np.dot(A_inv, b2), np.dot(A_inv, b3)

(array([[-1.],
        [ 4.]]),
 array([[3.],
        [1.]]),
 array([[2.],
        [6.]]))

In [32]:
T = np.array([[1, -1, 0],
              [0, 2, 1],
              [-1, 1, 1]])
x1 = np.array([1, 1]).reshape(-1, 1)
x2 = np.array([2, 1]).reshape(-1, 1)
A = np.array([[1, 0],
              [2, -3],
              [-3, 1]])
Lx1, Lx2 = np.dot(A, x1), np.dot(A, x2)
np.dot(np.linalg.inv(T), np.hstack([Lx1, Lx2]))

array([[ 1.,  4.],
       [ 0.,  2.],
       [-1., -3.]])

In [33]:
A = np.array([[1, -1],
              [1, 1]])
P = np.array([[0, -1],
              [1, 1]])
np.dot(np.dot(np.linalg.inv(P), A), P)

array([[ 0., -2.],
       [ 1.,  2.]])