In [1]:
import numpy as np
import sympy as sp

In [4]:
A = sp.Matrix([[0, 2, -7, -17],
               [2, 2, 4, 18],
               [3, 6, -5, 0]])
A.rref()

(Matrix([
 [1, 0, 0, 1],
 [0, 1, 0, 2],
 [0, 0, 1, 3]]),
 (0, 1, 2))

In [6]:
A = sp.Matrix([[1, 3, -2, 0, 2, 0, 0],
               [2, 6, -5, -2, 4, -3, -1],
               [0, 0, 5, 10, 0, 15, 5],
               [2, 6, 0, 8, 4, 18, 6]])
A.rref()

(Matrix([
 [1, 3, 0, 4, 2, 0,   0],
 [0, 0, 1, 2, 0, 0,   0],
 [0, 0, 0, 0, 0, 1, 1/3],
 [0, 0, 0, 0, 0, 0,   0]]),
 (0, 2, 5))

In [8]:
a = np.array([[1, 2, -1], [3, 1, 0]])
b = np.array([[-2, 1], [0, -3], [2, 1]])
np.dot(a, b)

array([[-4, -6],
       [-6,  0]])

In [9]:
a = np.array([[1, 2, -1],
              [3, 1, 0]])
b = np.array([[-2, 1],
              [0, -3],
              [2, 1]])
np.dot(b, a)

array([[ 1, -3,  2],
       [-9, -3,  0],
       [ 5,  5, -2]])

In [10]:
a = np.array([[-2, -5],
              [-1, -3]])
b = np.array([[-3, 5],
              [1, -2]])
np.dot(b, a)

array([[1, 0],
       [0, 1]])

In [11]:
np.linalg.inv(a)

array([[-3.,  5.],
       [ 1., -2.]])

In [12]:
A = sp.Matrix([[1, 6, 4, 1, 0, 0],
               [2, 4, -1, 0, 1, 0],
               [-1, 2, 5, 0, 0, 1]])
A.rref()

(Matrix([
 [1, 0, -11/4, 0, 1/4, -1/2],
 [0, 1,   9/8, 0, 1/8,  1/4],
 [0, 0,     0, 1,  -1,   -1]]),
 (0, 1, 3))

In [13]:
a = np.array([[1, 2, 3],
              [2, 5, 3],
              [1, 0, 8]])
b = np.array([[1],
              [3],
              [-1]])
np.dot(np.linalg.inv(a), b)

array([[-1.],
       [ 1.],
       [ 0.]])