In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from matplotlib import rc
import seaborn as sns
from scipy import stats as ss
import statsmodels.api as sm
import statsmodels.formula.api as smf

In [2]:
O = np.array([18,55,27])
Pr = np.array([0.25,0.50,0.25])
n = O.sum()
E = n * Pr
ddof = len(O)-1
O, Pr, n, E, ddof

(array([18, 55, 27]),
 array([0.25, 0.5 , 0.25]),
 100,
 array([25., 50., 25.]),
 2)

In [6]:
chi2, p_value = ss.chisquare(O, E)
chi2, p_value

(2.62, 0.26982005638468687)

In [7]:
diet = np.array([[37,24,19],[17,33,20]])
column_names = ['Good', 'Normal', 'Bad']
row_names    = ['diet_A', 'diet_B']
table = pd.DataFrame(diet, columns=column_names, index=row_names)
table

Good  Normal  Bad
diet_A    37      24   19
diet_B    17      33   20

In [9]:
chi2, p_value, ddof, expected = ss.chi2_contingency(table)
chi2, p_value, ddof, expected

(8.22398544438018,
 0.01637511094543408,
 2,
 array([[28.8, 30.4, 20.8],
        [25.2, 26.6, 18.2]]))