In [2]:
import numpy as np
import sympy as sp

In [3]:
a = sp.Symbol('a')
b = sp.Symbol('b')
A = np.array([[1, -2],
              [-2, 8]])
x = np.array([a, b]).reshape(2, -1)
del_fx = np.dot(A, x)
del_fx

array([[a - 2*b],
       [-2*a + 8*b]], dtype=object)

In [4]:
f = 0.5 * np.dot(np.dot(x.transpose(), A), x)
f

array([[0.5*a*(a - 2*b) + 0.5*b*(-2*a + 8*b)]], dtype=object)

In [5]:
a0, b0 = 1, 2
eps = 1e-8
t = 0.01

In [6]:
x_list, y_list = [], []
x_list.append(a0)
y_list.append(b0)

In [7]:
a_k, b_k = a0, b0
iter = 0

In [8]:
def f(a0, a1, x, y):
    N = len(x)
    return 1/N * np.sum((a0 + a1*x - y) ** 2)

def dfda0(a0, a1, x, y):
    N = len(x)
    return 2/N * np.sum(a0 + a1*x - y)

def dfda1(a0, a1, x, y):
    N = len(x)
    return 2/N * np.sum((a0 + a1*x - y) * x)

In [9]:
x = np.array([1, 2, 3, 4, 5])
y = np.array([1, 3, 5, 3, 7])
N = len(x)

In [10]:
a0_0, a1_0 = 0, 0
eps = 1e-8

In [11]:
X = np.array([[104, -72],
              [-72, 146]])
np.linalg.eig(X)

(array([ 50., 200.]),
 array([[-0.8,  0.6],
        [-0.6, -0.8]]))

In [13]:
A = np.array([[-2, 11],
              [-10, 5]])
np.linalg.svd(A)

(array([[-0.70710678, -0.70710678],
        [-0.70710678,  0.70710678]]),
 array([14.14213562,  7.07106781]),
 array([[ 0.6, -0.8],
        [-0.8, -0.6]]))