In [4]:
import torch
import numpy as np

In [5]:
example_array = np.array([[1, 2], [3, 4]])
ft = torch.FloatTensor(example_array)
ft

tensor([[1., 2.],
        [3., 4.]])

In [6]:
lt = torch.LongTensor(example_array)
lt

tensor([[1, 2],
        [3, 4]])

In [7]:
bt = torch.ByteTensor(example_array)
bt

tensor([[1, 2],
        [3, 4]], dtype=torch.uint8)

In [10]:
x = torch.FloatTensor(3, 2, 3)
x

tensor([[[9.1837e-39, 4.6837e-39, 9.9184e-39],
         [9.0000e-39, 1.0561e-38, 1.0653e-38]],

        [[4.1327e-39, 8.9082e-39, 9.8265e-39],
         [9.4592e-39, 1.0561e-38, 1.0745e-38]],

        [[9.9184e-39, 9.6429e-39, 4.6837e-39],
         [4.5000e-39, 4.5918e-39, 4.2245e-39]]])

In [11]:
x = torch.from_numpy(example_array)
x

tensor([[1, 2],
        [3, 4]], dtype=torch.int32)

In [12]:
x.numpy()

array([[1, 2],
       [3, 4]])

In [13]:
ft.long()

tensor([[1, 2],
        [3, 4]])

In [16]:
x = torch.FloatTensor([[[1, 2], [3, 4]], [[5, 6], [7, 8]], [[9, 10], [11, 12]]])
x.size(), x.shape

(torch.Size([3, 2, 2]), torch.Size([3, 2, 2]))

In [18]:
x.dim()

3

In [19]:
a = torch.FloatTensor(np.array([[1, 2], [3, 4]]))
b = torch.FloatTensor(np.array([[2, 2], [3, 3]]))

In [22]:
a + b, a ** b, a == b

(tensor([[3., 4.],
         [6., 7.]]),
 tensor([[ 1.,  4.],
         [27., 64.]]),
 tensor([[False,  True],
         [ True, False]]))

In [29]:
a.add(b), a.mul(b)

(tensor([[3., 4.],
         [6., 7.]]),
 tensor([[ 2.,  4.],
         [ 9., 12.]]))

In [31]:
a.sum(), a.mean()

(tensor(10.), tensor(2.5000))

In [35]:
a.sum(dim=0)

tensor([4., 6.])

In [37]:
y = 1
a + y

tensor([[2., 3.],
        [4., 5.]])

In [43]:
y = torch.FloatTensor([[3], [5]])
z = torch.FloatTensor([[3, 5]])
a + y, a + z

(tensor([[4., 5.],
         [8., 9.]]),
 tensor([[4., 7.],
         [6., 9.]]))

In [44]:
x = torch.FloatTensor([[[1, 2], [3, 4]], [[5, 6], [7, 8]], [[9, 10], [11, 12]]])
x.shape

torch.Size([3, 2, 2])

In [45]:
x.view(12), x.view(3, 4), x.view(3, 1, 4)

(tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.]),
 tensor([[ 1.,  2.,  3.,  4.],
         [ 5.,  6.,  7.,  8.],
         [ 9., 10., 11., 12.]]),
 tensor([[[ 1.,  2.,  3.,  4.]],
 
         [[ 5.,  6.,  7.,  8.]],
 
         [[ 9., 10., 11., 12.]]]))

In [47]:
x.view(-1), x.view(3, -1), x.view(-1, 1, 4)

(tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.]),
 tensor([[ 1.,  2.,  3.,  4.],
         [ 5.,  6.,  7.,  8.],
         [ 9., 10., 11., 12.]]),
 tensor([[[ 1.,  2.,  3.,  4.]],
 
         [[ 5.,  6.,  7.,  8.]],
 
         [[ 9., 10., 11., 12.]]]))

In [48]:
y = x.view(3, -1)
x.storage().data_ptr() == y.storage().data_ptr()

True

In [49]:
y = x.reshape(3, -1)
x.storage().data_ptr() == y.storage().data_ptr()

True

In [50]:
x = torch.FloatTensor([[[1, 2], [3, 4]]])
x.shape

torch.Size([1, 2, 2])

In [51]:
x.squeeze()

tensor([[1., 2.],
        [3., 4.]])

In [53]:
x.squeeze(0).shape, x.squeeze(1).shape

(torch.Size([2, 2]), torch.Size([1, 2, 2]))

In [54]:
y = x.squeeze()
y

tensor([[1., 2.],
        [3., 4.]])

In [56]:
y.unsqueeze(0), y.unsqueeze(1), y.unsqueeze(-1), y.unsqueeze(-1).shape

(tensor([[[1., 2.],
          [3., 4.]]]),
 tensor([[[1., 2.]],
 
         [[3., 4.]]]),
 tensor([[[1.],
          [2.]],
 
         [[3.],
          [4.]]]),
 torch.Size([2, 2, 1]))

In [57]:
y.reshape(2, 2, 1)

tensor([[[1.],
         [2.]],

        [[3.],
         [4.]]])

In [58]:
x = torch.FloatTensor([[[1, 2], [3, 4]], [[5, 6], [7, 8]], [[9, 10], [11, 12]]])
x.shape

torch.Size([3, 2, 2])

In [59]:
x[0]

tensor([[1., 2.],
        [3., 4.]])

In [61]:
x[:, 0], x[:, 1]

(tensor([[ 1.,  2.],
         [ 5.,  6.],
         [ 9., 10.]]),
 tensor([[ 3.,  4.],
         [ 7.,  8.],
         [11., 12.]]))

In [64]:
x = torch.FloatTensor(10, 4)
splits = x.split(4, dim=0)
splits

(tensor([[3.4546e+28, 6.3759e-43, 2.2724e+33, 6.3759e-43],
         [4.2039e-45, 7.0065e-45, 3.4752e+28, 6.3759e-43],
         [5.5013e+28, 6.3759e-43, 1.0849e+29, 6.3759e-43],
         [0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00]]),
 tensor([[1.4013e-45, 0.0000e+00, 0.0000e+00, 0.0000e+00],
         [0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00],
         [0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00],
         [0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00]]),
 tensor([[0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00],
         [2.1019e-44, 0.0000e+00, 0.0000e+00, 0.0000e+00]]))

In [72]:
x = torch.FloatTensor(8, 4)
chunks = x.chunk(8, dim=0)
x, chunks

(tensor([[2.0202e+36, 6.3759e-43, 1.4013e-45, 0.0000e+00],
         [5.6052e-45, 0.0000e+00, 0.0000e+00, 0.0000e+00],
         [0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00],
         [0.0000e+00, 0.0000e+00, 1.4013e-45, 0.0000e+00],
         [0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00],
         [0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00],
         [3.9236e-44, 0.0000e+00, 5.6052e-45, 0.0000e+00],
         [9.1844e-41, 1.1551e-40, 2.2960e-41, 4.1478e-43]]),
 (tensor([[2.0202e+36, 6.3759e-43, 1.4013e-45, 0.0000e+00]]),
  tensor([[5.6052e-45, 0.0000e+00, 0.0000e+00, 0.0000e+00]]),
  tensor([[0., 0., 0., 0.]]),
  tensor([[0.0000e+00, 0.0000e+00, 1.4013e-45, 0.0000e+00]]),
  tensor([[0., 0., 0., 0.]]),
  tensor([[0., 0., 0., 0.]]),
  tensor([[3.9236e-44, 0.0000e+00, 5.6052e-45, 0.0000e+00]]),
  tensor([[9.1844e-41, 1.1551e-40, 2.2960e-41, 4.1478e-43]])))

In [73]:
x = torch.arange(10).reshape(5, 2)
x.split(3, dim=0), x.chunk(3, dim=0)


((tensor([[0, 1],
          [2, 3],
          [4, 5]]),
  tensor([[6, 7],
          [8, 9]])),
 (tensor([[0, 1],
          [2, 3]]),
  tensor([[4, 5],
          [6, 7]]),
  tensor([[8, 9]])))

In [81]:
x = torch.FloatTensor([[[1, 1], [2, 2]], [[3, 3], [4, 4]], [[5, 5], [6, 6]]])
indice = torch.LongTensor([1, 2])
x.shape

torch.Size([3, 2, 2])

In [82]:
x.index_select(dim=0, index=indice)

tensor([[[3., 3.],
         [4., 4.]],

        [[5., 5.],
         [6., 6.]]])

In [84]:
x = torch.FloatTensor([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
y = torch.FloatTensor([[10, 11, 12], [13, 14, 15], [16, 17, 18]])
x.shape, y.shape

(torch.Size([3, 3]), torch.Size([3, 3]))

In [85]:
torch.concat([x, y], dim=0)

tensor([[ 1.,  2.,  3.],
        [ 4.,  5.,  6.],
        [ 7.,  8.,  9.],
        [10., 11., 12.],
        [13., 14., 15.],
        [16., 17., 18.]])

In [90]:
torch.stack([x, y]), torch.stack([x, y], dim=0)

(tensor([[[ 1.,  2.,  3.],
          [ 4.,  5.,  6.],
          [ 7.,  8.,  9.]],
 
         [[10., 11., 12.],
          [13., 14., 15.],
          [16., 17., 18.]]]),
 tensor([[[ 1.,  2.,  3.],
          [ 4.,  5.,  6.],
          [ 7.,  8.,  9.]],
 
         [[10., 11., 12.],
          [13., 14., 15.],
          [16., 17., 18.]]]))

In [91]:
torch.stack([x, y], dim=1), torch.stack([x, y], dim=1).shape, torch.stack([x, y], dim=2)

(tensor([[[ 1.,  2.,  3.],
          [10., 11., 12.]],
 
         [[ 4.,  5.,  6.],
          [13., 14., 15.]],
 
         [[ 7.,  8.,  9.],
          [16., 17., 18.]]]),
 torch.Size([3, 2, 3]),
 tensor([[[ 1., 10.],
          [ 2., 11.],
          [ 3., 12.]],
 
         [[ 4., 13.],
          [ 5., 14.],
          [ 6., 15.]],
 
         [[ 7., 16.],
          [ 8., 17.],
          [ 9., 18.]]]))

In [94]:
d = 0
#z = torch.stack([x, y], dim=d)
z = torch.concat([x.unsqueeze(d), y.unsqueeze(d)], dim=d)
z

tensor([[[ 1.,  2.,  3.],
         [ 4.,  5.,  6.],
         [ 7.,  8.,  9.]],

        [[10., 11., 12.],
         [13., 14., 15.],
         [16., 17., 18.]]])

In [95]:
x = torch.FloatTensor([[[1, 2]], [[3, 4]]])
x.shape

torch.Size([2, 1, 2])

In [96]:
x.expand(2, 3, 2)

tensor([[[1., 2.],
         [1., 2.],
         [1., 2.]],

        [[3., 4.],
         [3., 4.],
         [3., 4.]]])

In [99]:
torch.concat([x] * 3, dim=1)

tensor([[[1., 2.],
         [1., 2.],
         [1., 2.]],

        [[3., 4.],
         [3., 4.],
         [3., 4.]]])

In [100]:
[x] * 3

[tensor([[[1., 2.]],
 
         [[3., 4.]]]),
 tensor([[[1., 2.]],
 
         [[3., 4.]]]),
 tensor([[[1., 2.]],
 
         [[3., 4.]]])]

In [102]:
x = torch.randperm(10).reshape(5, 2)
x

tensor([[8, 0],
        [6, 9],
        [7, 5],
        [4, 1],
        [3, 2]])

In [103]:
x = torch.randperm(3 ** 3).reshape(3, 3, -1)
x

tensor([[[ 7, 17,  2],
         [24, 11, 18],
         [20, 16,  8]],

        [[ 9, 19,  5],
         [10,  6, 14],
         [13, 22,  0]],

        [[26, 23, 12],
         [21,  4, 15],
         [ 3,  1, 25]]])

In [107]:
x.argmax(dim=-1), x.argmax(dim=1), x.argmax(dim=0)

(tensor([[1, 0, 0],
         [1, 2, 1],
         [0, 0, 2]]),
 tensor([[1, 0, 1],
         [2, 2, 1],
         [0, 0, 2]]),
 tensor([[2, 2, 2],
         [0, 0, 0],
         [0, 1, 2]]))

In [108]:
torch.topk(x, k=1, dim=-1)

torch.return_types.topk(
values=tensor([[[17],
         [24],
         [20]],

        [[19],
         [14],
         [22]],

        [[26],
         [21],
         [25]]]),
indices=tensor([[[1],
         [0],
         [0]],

        [[1],
         [2],
         [1]],

        [[0],
         [0],
         [2]]]))

In [109]:
x.topk(k=1, dim=-1)

torch.return_types.topk(
values=tensor([[[17],
         [24],
         [20]],

        [[19],
         [14],
         [22]],

        [[26],
         [21],
         [25]]]),
indices=tensor([[[1],
         [0],
         [0]],

        [[1],
         [2],
         [1]],

        [[0],
         [0],
         [2]]]))

In [110]:
values, indices = x.topk(k=2, dim=-1)
indices

tensor([[[1, 0],
         [0, 2],
         [0, 1]],

        [[1, 0],
         [2, 0],
         [1, 0]],

        [[0, 1],
         [0, 2],
         [2, 0]]])

In [114]:
values, indices = x.sort(dim=0, descending=True)
values

tensor([[[26, 23, 12],
         [24, 11, 18],
         [20, 22, 25]],

        [[ 9, 19,  5],
         [21,  6, 15],
         [13, 16,  8]],

        [[ 7, 17,  2],
         [10,  4, 14],
         [ 3,  1,  0]]])

In [115]:
x = torch.FloatTensor([i for i in range(3 ** 2)]).reshape(3, -1)
x

tensor([[0., 1., 2.],
        [3., 4., 5.],
        [6., 7., 8.]])

In [116]:
mask = x > 4
mask

tensor([[False, False, False],
        [False, False,  True],
        [ True,  True,  True]])

In [118]:
x.masked_fill(mask, value=-1)

tensor([[ 0.,  1.,  2.],
        [ 3.,  4., -1.],
        [-1., -1., -1.]])

In [119]:
torch.ones(2, 3), torch.zeros(2, 3)

(tensor([[1., 1., 1.],
         [1., 1., 1.]]),
 tensor([[0., 0., 0.],
         [0., 0., 0.]]))

In [120]:
x = torch.FloatTensor([i + 1 for i in range(6)]).reshape(2, -1)
x

tensor([[1., 2., 3.],
        [4., 5., 6.]])

In [122]:
torch.ones_like(x)

tensor([[1., 1., 1.],
        [1., 1., 1.]])