In [1]:
import torch
import torch.nn as nn
import torch.nn.functional as F
import numpy as np

In [2]:
target = torch.FloatTensor([i * 0.1 + 0.1 for i in range(9)]).reshape(3, 3)

In [3]:
x = torch.rand_like(target)
x.requires_grad = True

In [4]:
loss = F.mse_loss(x, target)
loss

tensor(0.0540, grad_fn=<MseLossBackward0>)

In [5]:
thres = 1e-5
learning_rate = 0.5
iter_cnt = 0

while loss > thres:
    iter_cnt += 1
    loss.backward()
    x = x - learning_rate * x.grad

    x.detach_()
    x.requires_grad_(True)

    loss = F.mse_loss(x, target)

    print(f'{iter_cnt}-th Loss: {loss}')
    print(x)

1-th Loss: 0.04266321659088135
tensor([[0.2232, 0.2896, 0.1212],
        [0.5963, 0.6197, 0.6330],
        [0.7647, 0.2841, 0.8325]], requires_grad=True)
2-th Loss: 0.03370920196175575
tensor([[0.2096, 0.2796, 0.1411],
        [0.5745, 0.6064, 0.6293],
        [0.7575, 0.3415, 0.8400]], requires_grad=True)
3-th Loss: 0.02663443237543106
tensor([[0.1974, 0.2708, 0.1588],
        [0.5551, 0.5946, 0.6261],
        [0.7511, 0.3924, 0.8467]], requires_grad=True)
4-th Loss: 0.02104448899626732
tensor([[0.1866, 0.2629, 0.1744],
        [0.5379, 0.5841, 0.6232],
        [0.7454, 0.4377, 0.8526]], requires_grad=True)
5-th Loss: 0.01662774197757244
tensor([[0.1769, 0.2559, 0.1884],
        [0.5226, 0.5747, 0.6206],
        [0.7404, 0.4780, 0.8579]], requires_grad=True)
6-th Loss: 0.013137970119714737
tensor([[0.1684, 0.2497, 0.2008],
        [0.5089, 0.5664, 0.6183],
        [0.7359, 0.5137, 0.8625]], requires_grad=True)
7-th Loss: 0.010380617342889309
tensor([[0.1608, 0.2442, 0.2118],
        [

In [6]:
x = torch.FloatTensor([i + 1 for i in range(4)]).reshape(2, 2).requires_grad_(True)

In [7]:
x1 = x + 2
x2 = x - 2
x3 = x1 * x2
y = x3.sum()

In [9]:
y.backward()

In [10]:
x.grad

tensor([[2., 4.],
        [6., 8.]])