In [13]:
import torch
import torch.nn as nn
import numpy as np

In [3]:
x = torch.FloatTensor([i + 1 for i in range(6)]).reshape(3, -1)
y = torch.FloatTensor([1, 2]).expand(2, 2)
x, y

(tensor([[1., 2.],
         [3., 4.],
         [5., 6.]]),
 tensor([[1., 2.],
         [1., 2.]]))

In [4]:
x.matmul(y)

tensor([[ 3.,  6.],
        [ 7., 14.],
        [11., 22.]])

In [7]:
x = torch.randperm(3 * 3 * 2).reshape(3, 3, 2)
y = torch.randperm(3 * 2 * 3).reshape(3, 2, 3)
x, y

(tensor([[[11, 15],
          [ 5, 14],
          [ 2,  3]],
 
         [[17,  6],
          [ 9,  8],
          [10,  4]],
 
         [[16,  0],
          [ 7, 13],
          [12,  1]]]),
 tensor([[[ 1,  9, 12],
          [10,  8,  5]],
 
         [[ 2, 17, 14],
          [13,  3,  0]],
 
         [[15,  6,  7],
          [16,  4, 11]]]))

In [8]:
x.bmm(y)

tensor([[[161, 219, 207],
         [145, 157, 130],
         [ 32,  42,  39]],

        [[112, 307, 238],
         [122, 177, 126],
         [ 72, 182, 140]],

        [[240,  96, 112],
         [313,  94, 192],
         [196,  76,  95]]])

In [9]:
W = torch.FloatTensor([i + 1 for i in range(6)]).reshape(3, 2)
b = torch.FloatTensor([2, 2])

In [10]:
def linear(x, W, b):
    y = torch.matmul(x, W) + b
    return y

In [12]:
x = torch.FloatTensor(4, 3)
y = linear(x, W, b)
x, y

(tensor([[9.2755e-39, 8.9082e-39, 9.9184e-39],
         [8.4490e-39, 9.6429e-39, 1.0653e-38],
         [1.0469e-38, 4.2246e-39, 1.0378e-38],
         [9.6429e-39, 9.2755e-39, 1.0928e-38]]),
 tensor([[2., 2.],
         [2., 2.],
         [2., 2.],
         [2., 2.]]))

In [14]:
class MyLinear(nn.Module):
    def __init__(self, input_dim=3, output_dim=2):
        self.input_dim = input_dim
        self.output_dim = output_dim

        super().__init__()

        self.W = torch.FloatTensor(input_dim, output_dim)
        self.b = torch.FloatTensor(output_dim)

    def forward(self, x):
        y = torch.matmul(x, self.W) + self.b
        return y

In [15]:
linear = MyLinear(3, 2)
y = linear(x)
y

tensor([[2.1120e+20, 6.7121e-07],
        [2.1120e+20, 6.7121e-07],
        [2.1120e+20, 6.7121e-07],
        [2.1120e+20, 6.7121e-07]])

In [16]:
class MyLinear(nn.Module):
    def __init__(self, input_dim=3, output_dim=2):
        self.input_dim = input_dim
        self.output_dim = output_dim

        super().__init__()

        self.W = nn.Parameter(torch.FloatTensor(input_dim, output_dim))
        self.b = nn.Parameter(torch.FloatTensor(output_dim))

    def forward(self, x):
        y = torch.matmul(x, self.W) + self.b
        return y

In [17]:
linear = MyLinear(3, 2)
y = linear(x)
y

tensor([[6.0049e-16, 7.0866e-07],
        [6.5002e-16, 7.6116e-07],
        [2.8478e-16, 7.4147e-07],
        [6.2526e-16, 7.8083e-07]], grad_fn=<AddBackward0>)

In [19]:
for parameter in linear.parameters():
    print(parameter)

Parameter containing:
tensor([[6.8611e-07, 1.0324e-05],
        [6.7409e+22, 2.6223e-09],
        [5.2158e-11, 7.1450e+31]], requires_grad=True)
Parameter containing:
tensor([0., 0.], requires_grad=True)


In [21]:
linear = nn.Linear(3, 2)
y = linear(x)
y

tensor([[-0.3591,  0.4191],
        [-0.3591,  0.4191],
        [-0.3591,  0.4191],
        [-0.3591,  0.4191]], grad_fn=<AddmmBackward0>)

In [22]:
for parameter in linear.parameters():
    print(parameter)

Parameter containing:
tensor([[ 0.2526,  0.5104, -0.0763],
        [ 0.5558,  0.0944,  0.5011]], requires_grad=True)
Parameter containing:
tensor([-0.3591,  0.4191], requires_grad=True)
