In [1]:
import torch
import torch.nn as nn
import numpy as np

In [2]:
x = torch.FloatTensor([i + 1 for i in range(6)]).reshape(3, -1)
y = torch.FloatTensor([1, 2]).expand(2, 2)
x, y

(tensor([[1., 2.],
         [3., 4.],
         [5., 6.]]),
 tensor([[1., 2.],
         [1., 2.]]))

In [3]:
z = torch.matmul(x, y)
z

tensor([[ 3.,  6.],
        [ 7., 14.],
        [11., 22.]])

In [4]:
x = torch.randperm(3 * 3 * 2).reshape(3, 3, 2)
y = torch.randperm(3 * 2 * 3).reshape(3, 2, 3)
x, y

(tensor([[[ 9, 11],
          [ 2,  7],
          [ 3, 13]],
 
         [[12, 17],
          [ 6,  8],
          [16, 10]],
 
         [[14,  0],
          [ 5,  4],
          [ 1, 15]]]),
 tensor([[[17,  7,  1],
          [ 5, 14, 15]],
 
         [[16,  9, 10],
          [ 4,  8, 11]],
 
         [[13,  2,  0],
          [ 6, 12,  3]]]))

In [5]:
torch.bmm(x, y)

tensor([[[208, 217, 174],
         [ 69, 112, 107],
         [116, 203, 198]],

        [[260, 244, 307],
         [128, 118, 148],
         [296, 224, 270]],

        [[182,  28,   0],
         [ 89,  58,  12],
         [103, 182,  45]]])

In [6]:
class MyLinear(nn.Module):
    def __init__(self, input_dim=3, output_dim=2):
        self.input_dim = input_dim
        self.output_dim = output_dim
        super().__init__()

        self.W = nn.Parameter(torch.FloatTensor(input_dim, output_dim))
        self.b = nn.Parameter(torch.FloatTensor(output_dim))
    
    def forward(self, x):
        y = torch.matmul(x, self.W) + self.b
        return y

In [7]:
linear = MyLinear(4, 3)
for p in linear.parameters():
    print(p)

Parameter containing:
tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]], requires_grad=True)
Parameter containing:
tensor([8.9082e-39, 6.9796e-39, 9.0919e-39], requires_grad=True)


In [8]:
linear = nn.Linear(4, 3)
for p in linear.parameters():
    print(p)

Parameter containing:
tensor([[-0.2278,  0.3572, -0.2498,  0.2422],
        [-0.3671, -0.2084, -0.4382,  0.4259],
        [ 0.1288, -0.1327, -0.0721, -0.2400]], requires_grad=True)
Parameter containing:
tensor([-0.1572, -0.0997, -0.3980], requires_grad=True)


In [9]:
class MyLinear(nn.Module):
    def __init__(self, input_dim=3, output_dim=2):
        self.input_dim = input_dim
        self.output_dim = output_dim
        super().__init__()

        self.linear = nn.Linear(input_dim, output_dim)
    
    def forward(self, x):
        y = self.linear(x)
        return y