In [2]:
import torch
import torch.nn as nn
import torch.nn.functional as F
import numpy as np

In [12]:
target = torch.FloatTensor([i + 1 for i in range(9)]).reshape(3, 3)

In [13]:
x = torch.rand_like(target)
x.requires_grad = True
x

tensor([[0.2538, 0.2181, 0.8582],
        [0.8002, 0.8241, 0.6895],
        [0.8296, 0.3412, 0.1851]], requires_grad=True)

In [14]:
loss = F.mse_loss(x, target)
loss

tensor(26.5145, grad_fn=<MseLossBackward0>)

In [15]:
thrs = 1e-5
learning_rate = 1
iter_cnt = 0

while loss > thrs:
    iter_cnt += 1
    loss.backward()
    x = x - learning_rate * x.grad

    x.detach_()
    x.requires_grad_(True)

    loss = F.mse_loss(x, target)

    print(f'{iter_cnt}-th Loss: {loss:.4e}')
    print(x)

1-th Loss: 1.6040e+01
tensor([[0.4196, 0.6141, 1.3342],
        [1.5112, 1.7521, 1.8696],
        [2.2008, 2.0432, 2.1439]], requires_grad=True)
2-th Loss: 9.7030e+00
tensor([[0.5486, 0.9221, 1.7043],
        [2.0643, 2.4739, 2.7875],
        [3.2673, 3.3669, 3.6675]], requires_grad=True)
3-th Loss: 5.8697e+00
tensor([[0.6489, 1.1616, 1.9923],
        [2.4945, 3.0352, 3.5014],
        [4.0968, 4.3965, 4.8525]], requires_grad=True)
4-th Loss: 3.5508e+00
tensor([[0.7269, 1.3479, 2.2162],
        [2.8290, 3.4718, 4.0566],
        [4.7419, 5.1973, 5.7742]], requires_grad=True)
5-th Loss: 2.1480e+00
tensor([[0.7876, 1.4928, 2.3904],
        [3.0892, 3.8114, 4.4885],
        [5.2437, 5.8201, 6.4910]], requires_grad=True)
6-th Loss: 1.2994e+00
tensor([[0.8348, 1.6055, 2.5259],
        [3.2916, 4.0756, 4.8244],
        [5.6340, 6.3045, 7.0486]], requires_grad=True)
7-th Loss: 7.8607e-01
tensor([[0.8715, 1.6932, 2.6312],
        [3.4490, 4.2810, 5.0856],
        [5.9376, 6.6813, 7.4822]], requi

In [16]:
x = torch.FloatTensor([i + 1 for i in range(4)]).reshape(2, 2).requires_grad_(True)

In [17]:
x1 = x + 2
x2 = x - 2
x3 = x1 * x2
y = x3.sum()

In [18]:
x1, x2, x3, y

(tensor([[3., 4.],
         [5., 6.]], grad_fn=<AddBackward0>),
 tensor([[-1.,  0.],
         [ 1.,  2.]], grad_fn=<SubBackward0>),
 tensor([[-3.,  0.],
         [ 5., 12.]], grad_fn=<MulBackward0>),
 tensor(14., grad_fn=<SumBackward0>))

In [19]:
y.backward()

In [23]:
print(x.grad)

tensor([[2., 4.],
        [6., 8.]])


In [24]:
x3.detach_()

tensor([[-3.,  0.],
        [ 5., 12.]])

In [25]:
print(x.grad)

tensor([[2., 4.],
        [6., 8.]])
