In [2]:
import torch
import numpy as np

In [3]:
ft = torch.FloatTensor([[1, 2], [3, 4]])
ft

tensor([[1., 2.],
        [3., 4.]])

In [4]:
ft = torch.LongTensor(3, 2)
ft

tensor([[0, 0],
        [0, 0],
        [0, 0]])

In [5]:
x = np.array([[1, 2], [3, 4]])
torch.from_numpy(x).numpy()

array([[1, 2],
       [3, 4]])

In [6]:
x = torch.FloatTensor([[[1, 2], [3, 4]], [[5, 6], [7, 8]], [[9, 10], [11, 12]]])
x.size(), x.shape

(torch.Size([3, 2, 2]), torch.Size([3, 2, 2]))

In [7]:
x.dim(), len(x.size())

(3, 3)

In [8]:
a = torch.FloatTensor(np.array([[1, 2], [3, 4]]))
b = torch.FloatTensor(np.array([[2, 2], [3, 3]]))

In [9]:
a + b, a - b, a * b, a / b

(tensor([[3., 4.],
         [6., 7.]]),
 tensor([[-1.,  0.],
         [ 0.,  1.]]),
 tensor([[ 2.,  4.],
         [ 9., 12.]]),
 tensor([[0.5000, 1.0000],
         [1.0000, 1.3333]]))

In [11]:
a.sum(), a.mean()

(tensor(10.), tensor(2.5000))

In [12]:
a.sum(dim=0)

tensor([4., 6.])

In [13]:
y = 1
a + y

tensor([[2., 3.],
        [4., 5.]])

In [14]:
y = torch.FloatTensor([[3], [5]])
z = torch.FloatTensor([[3, 5]])
a + y, a + z

(tensor([[4., 5.],
         [8., 9.]]),
 tensor([[4., 7.],
         [6., 9.]]))

In [15]:
x = torch.FloatTensor([[[1, 2], [3, 4]], [[5, 6], [7, 8]], [[9, 10], [11, 12]]])
x.shape

torch.Size([3, 2, 2])

In [16]:
x.view(12), x.view(3, 4), x.view(3, 1, 4)

(tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.]),
 tensor([[ 1.,  2.,  3.,  4.],
         [ 5.,  6.,  7.,  8.],
         [ 9., 10., 11., 12.]]),
 tensor([[[ 1.,  2.,  3.,  4.]],
 
         [[ 5.,  6.,  7.,  8.]],
 
         [[ 9., 10., 11., 12.]]]))

In [17]:
y = x.view(3, 4)
x.storage().data_ptr() == y.storage().data_ptr()

C:\Users\admin\AppData\Local\Temp\ipykernel_13752\2008657820.py:2: UserWarning: TypedStorage is deprecated. It will be removed in the future and UntypedStorage will be the only storage class. This should only matter to you if you are using storages directly.  To access UntypedStorage directly, use tensor.untyped_storage() instead of tensor.storage()
  x.storage().data_ptr() == y.storage().data_ptr()


True

In [18]:
y = x.reshape(3, 4)
x.storage().data_ptr() == y.storage().data_ptr()

C:\Users\admin\AppData\Local\Temp\ipykernel_13752\3552180704.py:2: UserWarning: TypedStorage is deprecated. It will be removed in the future and UntypedStorage will be the only storage class. This should only matter to you if you are using storages directly.  To access UntypedStorage directly, use tensor.untyped_storage() instead of tensor.storage()
  x.storage().data_ptr() == y.storage().data_ptr()


True

In [19]:
x = torch.FloatTensor([[[1, 2], [3, 4]]])
x.shape

torch.Size([1, 2, 2])

In [20]:
x.squeeze()

tensor([[1., 2.],
        [3., 4.]])

In [21]:
x.squeeze(0).size(), x.squeeze(1).size()

(torch.Size([2, 2]), torch.Size([1, 2, 2]))

In [23]:
x.unsqueeze(-1).size()

torch.Size([1, 2, 2, 1])

In [24]:
x = torch.FloatTensor([[[1, 2], [3, 4]], [[5, 6], [7, 8]], [[9, 10], [11, 12]]])
x.shape

torch.Size([3, 2, 2])

In [25]:
x[0]

tensor([[1., 2.],
        [3., 4.]])

In [26]:
x[:, 0]

tensor([[ 1.,  2.],
        [ 5.,  6.],
        [ 9., 10.]])

In [27]:
x[:, :, 0]

tensor([[ 1.,  3.],
        [ 5.,  7.],
        [ 9., 11.]])

In [28]:
x = torch.FloatTensor(10, 4)
splits = x.split(4, dim=0)
splits

(tensor([[ 1.8888e+31,  4.1051e-41,  0.0000e+00,  0.0000e+00],
         [ 0.0000e+00,  0.0000e+00,  2.1019e-44,  0.0000e+00],
         [-3.5283e-31,  6.4039e-43, -1.3866e-14,  6.4039e-43],
         [ 0.0000e+00,  7.0065e-45,  0.0000e+00,  0.0000e+00]]),
 tensor([[0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00],
         [0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00],
         [1.4013e-45, 0.0000e+00, 0.0000e+00, 0.0000e+00],
         [0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00]]),
 tensor([[0., 0., 0., 0.],
         [0., 0., 0., 0.]]))

In [31]:
chunks = x.chunk(4, dim=0)
chunks

(tensor([[ 1.8888e+31,  4.1051e-41,  0.0000e+00,  0.0000e+00],
         [ 0.0000e+00,  0.0000e+00,  2.1019e-44,  0.0000e+00],
         [-3.5283e-31,  6.4039e-43, -1.3866e-14,  6.4039e-43]]),
 tensor([[0.0000e+00, 7.0065e-45, 0.0000e+00, 0.0000e+00],
         [0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00],
         [0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00]]),
 tensor([[1.4013e-45, 0.0000e+00, 0.0000e+00, 0.0000e+00],
         [0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00],
         [0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00]]),
 tensor([[0., 0., 0., 0.]]))

In [37]:
x = torch.FloatTensor([[[1, 1], [2, 2]], [[3, 3], [4, 4]], [[5, 5], [6, 6]]])
indice = torch.LongTensor([2, 1, 0])
x.shape

torch.Size([3, 2, 2])

In [38]:
torch.index_select(x, dim=0, index=indice)

tensor([[[5., 5.],
         [6., 6.]],

        [[3., 3.],
         [4., 4.]],

        [[1., 1.],
         [2., 2.]]])

In [39]:
x = torch.FloatTensor([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
y = torch.FloatTensor([[10, 11, 12], [13, 14, 15], [16, 17, 18]])
x.shape, y.shape

(torch.Size([3, 3]), torch.Size([3, 3]))

In [40]:
torch.concat([x, y], dim=0)

tensor([[ 1.,  2.,  3.],
        [ 4.,  5.,  6.],
        [ 7.,  8.,  9.],
        [10., 11., 12.],
        [13., 14., 15.],
        [16., 17., 18.]])

In [43]:
torch.stack([x, y]), torch.stack([x, y], dim=0), torch.stack([x, y], dim=1)

(tensor([[[ 1.,  2.,  3.],
          [ 4.,  5.,  6.],
          [ 7.,  8.,  9.]],
 
         [[10., 11., 12.],
          [13., 14., 15.],
          [16., 17., 18.]]]),
 tensor([[[ 1.,  2.,  3.],
          [ 4.,  5.,  6.],
          [ 7.,  8.,  9.]],
 
         [[10., 11., 12.],
          [13., 14., 15.],
          [16., 17., 18.]]]),
 tensor([[[ 1.,  2.,  3.],
          [10., 11., 12.]],
 
         [[ 4.,  5.,  6.],
          [13., 14., 15.]],
 
         [[ 7.,  8.,  9.],
          [16., 17., 18.]]]))

In [46]:
d = 1
torch.concat([x.unsqueeze(d), y.unsqueeze(d)], dim=d)

tensor([[[ 1.,  2.,  3.],
         [10., 11., 12.]],

        [[ 4.,  5.,  6.],
         [13., 14., 15.]],

        [[ 7.,  8.,  9.],
         [16., 17., 18.]]])

In [47]:
x = torch.FloatTensor([[[1, 2]], [[3, 4]]])
x.shape

torch.Size([2, 1, 2])

In [49]:
x.expand(2, 3, 2), torch.concat([x] * 3, dim=1)

(tensor([[[1., 2.],
          [1., 2.],
          [1., 2.]],
 
         [[3., 4.],
          [3., 4.],
          [3., 4.]]]),
 tensor([[[1., 2.],
          [1., 2.],
          [1., 2.]],
 
         [[3., 4.],
          [3., 4.],
          [3., 4.]]]))

In [50]:
torch.randperm(10)

tensor([8, 9, 6, 2, 3, 1, 7, 0, 5, 4])

In [51]:
x = torch.randperm(3 ** 3).reshape(3, 3, -1)
x

tensor([[[24,  2, 16],
         [13, 15,  4],
         [ 8, 25,  1]],

        [[26, 12, 10],
         [ 7,  5, 11],
         [19, 17, 21]],

        [[ 9, 18,  6],
         [23,  3, 14],
         [22, 20,  0]]])

In [53]:
x.argmax(-1), x.argmax(0)

(tensor([[0, 1, 1],
         [0, 2, 2],
         [1, 0, 0]]),
 tensor([[1, 2, 0],
         [2, 0, 2],
         [2, 0, 1]]))

In [54]:
torch.topk(x, k=1, dim=-1)

torch.return_types.topk(
values=tensor([[[24],
         [15],
         [25]],

        [[26],
         [11],
         [21]],

        [[18],
         [23],
         [22]]]),
indices=tensor([[[0],
         [1],
         [1]],

        [[0],
         [2],
         [2]],

        [[1],
         [0],
         [0]]]))

In [55]:
torch.sort(x, dim=-1, descending=True)

torch.return_types.sort(
values=tensor([[[24, 16,  2],
         [15, 13,  4],
         [25,  8,  1]],

        [[26, 12, 10],
         [11,  7,  5],
         [21, 19, 17]],

        [[18,  9,  6],
         [23, 14,  3],
         [22, 20,  0]]]),
indices=tensor([[[0, 2, 1],
         [1, 0, 2],
         [1, 0, 2]],

        [[0, 1, 2],
         [2, 0, 1],
         [2, 0, 1]],

        [[1, 0, 2],
         [0, 2, 1],
         [0, 1, 2]]]))

In [56]:
x = torch.FloatTensor([i for i in range(3 ** 2)]).reshape(3, -1)
x

tensor([[0., 1., 2.],
        [3., 4., 5.],
        [6., 7., 8.]])

In [57]:
mask = x > 4

In [58]:
x.masked_fill(mask, value=-1)

tensor([[ 0.,  1.,  2.],
        [ 3.,  4., -1.],
        [-1., -1., -1.]])

In [59]:
torch.ones(2, 3), torch.zeros(2, 3)

(tensor([[1., 1., 1.],
         [1., 1., 1.]]),
 tensor([[0., 0., 0.],
         [0., 0., 0.]]))

In [60]:
x = torch.FloatTensor([i + 1 for i in range(6)]).reshape(2, -1)
x

tensor([[1., 2., 3.],
        [4., 5., 6.]])

In [61]:
torch.ones_like(x), torch.zeros_like(x)

(tensor([[1., 1., 1.],
         [1., 1., 1.]]),
 tensor([[0., 0., 0.],
         [0., 0., 0.]]))