In [1]:
import torch
import torch.nn as nn
import torch.nn.functional as F
import numpy as np

In [2]:
target = torch.FloatTensor([i * 0.1 + 0.1 for i in range(9)]).reshape(3, 3)
target

tensor([[0.1000, 0.2000, 0.3000],
        [0.4000, 0.5000, 0.6000],
        [0.7000, 0.8000, 0.9000]])

In [3]:
x = torch.rand_like(target)
x.requires_grad = True
x

tensor([[0.1092, 0.2025, 0.4960],
        [0.1093, 0.8525, 0.4141],
        [0.1738, 0.8129, 0.3987]], requires_grad=True)

In [4]:
loss = F.mse_loss(x, target)
loss

tensor(0.0900, grad_fn=<MseLossBackward0>)

In [5]:
thres = 1e-5
lr = 0.1
iter_cnt = 0

In [6]:
while loss > thres:
    iter_cnt += 1
    loss.backward()
    x = x - lr*x.grad
    x.detach_()
    x.requires_grad_(True)
    loss = F.mse_loss(x, target)
    print(iter_cnt, loss)
    print(x)

1 tensor(0.0861, grad_fn=<MseLossBackward0>)
tensor([[0.1089, 0.2025, 0.4916],
        [0.1158, 0.8446, 0.4182],
        [0.1855, 0.8126, 0.4099]], requires_grad=True)
2 tensor(0.0823, grad_fn=<MseLossBackward0>)
tensor([[0.1087, 0.2024, 0.4874],
        [0.1221, 0.8370, 0.4222],
        [0.1969, 0.8123, 0.4208]], requires_grad=True)
3 tensor(0.0787, grad_fn=<MseLossBackward0>)
tensor([[0.1086, 0.2024, 0.4832],
        [0.1283, 0.8295, 0.4262],
        [0.2081, 0.8121, 0.4314]], requires_grad=True)
4 tensor(0.0752, grad_fn=<MseLossBackward0>)
tensor([[0.1084, 0.2023, 0.4791],
        [0.1343, 0.8222, 0.4301],
        [0.2190, 0.8118, 0.4418]], requires_grad=True)
5 tensor(0.0719, grad_fn=<MseLossBackward0>)
tensor([[0.1082, 0.2023, 0.4751],
        [0.1402, 0.8150, 0.4338],
        [0.2297, 0.8115, 0.4520]], requires_grad=True)
6 tensor(0.0687, grad_fn=<MseLossBackward0>)
tensor([[0.1080, 0.2022, 0.4713],
        [0.1460, 0.8080, 0.4375],
        [0.2402, 0.8113, 0.4620]], requires_gra

In [7]:
x = torch.FloatTensor([[1, 2],
                       [3, 4]]).requires_grad_(True)
x

tensor([[1., 2.],
        [3., 4.]], requires_grad=True)