In [1]:
import torch
import numpy as np

In [2]:
ft = torch.FloatTensor([[1, 2],
                        [3, 4]])
ft

tensor([[1., 2.],
        [3., 4.]])

In [5]:
lt = torch.LongTensor([[1, 2],
                       [3, 4]])
lt

tensor([[1, 2],
        [3, 4]])

In [7]:
bt = torch.ByteTensor([[1, 2],
                       [3, 4]])
bt

tensor([[1, 2],
        [3, 4]], dtype=torch.uint8)

In [8]:
x = torch.FloatTensor(3, 2)
x

tensor([[0.0000e+00, 7.7071e-44],
        [1.7585e-04, 4.4161e-05],
        [1.0675e-08, 8.3961e-07]])

In [10]:
xnp = np.array([[1, 2],
                [3, 4]])
xnp

array([[1, 2],
       [3, 4]])

In [11]:
x = torch.from_numpy(xnp)
x

tensor([[1, 2],
        [3, 4]], dtype=torch.int32)

In [12]:
x.numpy()

array([[1, 2],
       [3, 4]])

In [14]:
x.long(), x.float()

(tensor([[1, 2],
         [3, 4]]),
 tensor([[1., 2.],
         [3., 4.]]))

In [15]:
x = torch.FloatTensor([[[1, 2],
                        [3, 4]],
                       [[5, 6],
                        [7, 8]],
                       [[9, 10],
                        [11, 12]]])
x.size(), x.shape, x.dim()

(torch.Size([3, 2, 2]), torch.Size([3, 2, 2]), 3)

In [17]:
x.size(1), x.shape[2]

(2, 2)

In [20]:
a = torch.FloatTensor(np.array([[1, 2],
                                [3, 4]]))
b = torch.FloatTensor(np.array([[2, 2],
                                [3, 3]]))
a + b, a * b, a ** b, a == b

(tensor([[3., 4.],
         [6., 7.]]),
 tensor([[ 2.,  4.],
         [ 9., 12.]]),
 tensor([[ 1.,  4.],
         [27., 64.]]),
 tensor([[False,  True],
         [ True, False]]))

In [22]:
a.sum(), a.mean(), a.sum(dim=0), a.sum(dim=1)

(tensor(10.), tensor(2.5000), tensor([4., 6.]), tensor([3., 7.]))

In [23]:
torch.from_numpy(np.dot(a, b))

tensor([[ 8.,  8.],
        [18., 18.]])

In [26]:
x = torch.FloatTensor([[1, 2],
                       [4, 8]])
y = torch.FloatTensor([3, 5])
x + y, x + y.reshape(-1, 1)

(tensor([[ 4.,  7.],
         [ 7., 13.]]),
 tensor([[ 4.,  5.],
         [ 9., 13.]]))

In [27]:
x = torch.FloatTensor([[[1, 2],
                        [3, 4]],
                        [[5, 6],
                         [7, 8]],
                         [[9, 10],
                          [11, 12]]])
x.shape

torch.Size([3, 2, 2])

In [28]:
y = x.reshape(-1, 1, 4)
y, y.shape

(tensor([[[ 1.,  2.,  3.,  4.]],
 
         [[ 5.,  6.,  7.,  8.]],
 
         [[ 9., 10., 11., 12.]]]),
 torch.Size([3, 1, 4]))

In [30]:
y.squeeze(), y.squeeze().size()

(tensor([[ 1.,  2.,  3.,  4.],
         [ 5.,  6.,  7.,  8.],
         [ 9., 10., 11., 12.]]),
 torch.Size([3, 4]))

In [32]:
a.unsqueeze(1), a.unsqueeze(1).size()

(tensor([[[1., 2.]],
 
         [[3., 4.]]]),
 torch.Size([2, 1, 2]))