In [1]:
import torch
import numpy as np

In [2]:
ft = torch.FloatTensor([[1, 2],
                        [3, 4]])
ft

tensor([[1., 2.],
        [3., 4.]])

In [5]:
lt = torch.LongTensor([[1, 2],
                       [3, 4]])
lt

tensor([[1, 2],
        [3, 4]])

In [7]:
bt = torch.ByteTensor([[1, 2],
                       [3, 4]])
bt

tensor([[1, 2],
        [3, 4]], dtype=torch.uint8)

In [8]:
x = torch.FloatTensor(3, 2)
x

tensor([[0.0000e+00, 7.7071e-44],
        [1.7585e-04, 4.4161e-05],
        [1.0675e-08, 8.3961e-07]])

In [10]:
xnp = np.array([[1, 2],
                [3, 4]])
xnp

array([[1, 2],
       [3, 4]])

In [11]:
x = torch.from_numpy(xnp)
x

tensor([[1, 2],
        [3, 4]], dtype=torch.int32)

In [12]:
x.numpy()

array([[1, 2],
       [3, 4]])

In [14]:
x.long(), x.float()

(tensor([[1, 2],
         [3, 4]]),
 tensor([[1., 2.],
         [3., 4.]]))

In [15]:
x = torch.FloatTensor([[[1, 2],
                        [3, 4]],
                       [[5, 6],
                        [7, 8]],
                       [[9, 10],
                        [11, 12]]])
x.size(), x.shape, x.dim()

(torch.Size([3, 2, 2]), torch.Size([3, 2, 2]), 3)

In [17]:
x.size(1), x.shape[2]

(2, 2)

In [20]:
a = torch.FloatTensor(np.array([[1, 2],
                                [3, 4]]))
b = torch.FloatTensor(np.array([[2, 2],
                                [3, 3]]))
a + b, a * b, a ** b, a == b

(tensor([[3., 4.],
         [6., 7.]]),
 tensor([[ 2.,  4.],
         [ 9., 12.]]),
 tensor([[ 1.,  4.],
         [27., 64.]]),
 tensor([[False,  True],
         [ True, False]]))

In [22]:
a.sum(), a.mean(), a.sum(dim=0), a.sum(dim=1)

(tensor(10.), tensor(2.5000), tensor([4., 6.]), tensor([3., 7.]))

In [23]:
torch.from_numpy(np.dot(a, b))

tensor([[ 8.,  8.],
        [18., 18.]])

In [26]:
x = torch.FloatTensor([[1, 2],
                       [4, 8]])
y = torch.FloatTensor([3, 5])
x + y, x + y.reshape(-1, 1)

(tensor([[ 4.,  7.],
         [ 7., 13.]]),
 tensor([[ 4.,  5.],
         [ 9., 13.]]))

In [27]:
x = torch.FloatTensor([[[1, 2],
                        [3, 4]],
                        [[5, 6],
                         [7, 8]],
                         [[9, 10],
                          [11, 12]]])
x.shape

torch.Size([3, 2, 2])

In [28]:
y = x.reshape(-1, 1, 4)
y, y.shape

(tensor([[[ 1.,  2.,  3.,  4.]],
 
         [[ 5.,  6.,  7.,  8.]],
 
         [[ 9., 10., 11., 12.]]]),
 torch.Size([3, 1, 4]))

In [30]:
y.squeeze(), y.squeeze().size()

(tensor([[ 1.,  2.,  3.,  4.],
         [ 5.,  6.,  7.,  8.],
         [ 9., 10., 11., 12.]]),
 torch.Size([3, 4]))

In [32]:
a.unsqueeze(1), a.unsqueeze(1).size()

(tensor([[[1., 2.]],
 
         [[3., 4.]]]),
 torch.Size([2, 1, 2]))

In [37]:
x[0], x[:, 0], x[:, 1:2].size()

(tensor([[1., 2.],
         [3., 4.]]),
 tensor([[ 1.,  2.],
         [ 5.,  6.],
         [ 9., 10.]]),
 torch.Size([3, 1, 2]))

In [38]:
x = torch.FloatTensor(10, 4)
x.split(4, dim=0)

(tensor([[-9.7847e+14,  6.1097e-43, -9.7847e+14,  6.1097e-43],
         [-9.7846e+14,  6.1097e-43, -9.7846e+14,  6.1097e-43],
         [-9.7845e+14,  6.1097e-43, -9.7845e+14,  6.1097e-43],
         [-9.7845e+14,  6.1097e-43, -9.7844e+14,  6.1097e-43]]),
 tensor([[-9.7844e+14,  6.1097e-43, -9.7843e+14,  6.1097e-43],
         [-9.7843e+14,  6.1097e-43, -9.7842e+14,  6.1097e-43],
         [-9.7829e+14,  6.1097e-43, -9.7841e+14,  6.1097e-43],
         [-9.7819e+14,  6.1097e-43, -9.7835e+14,  6.1097e-43]]),
 tensor([[-9.7838e+14,  6.1097e-43, -9.7841e+14,  6.1097e-43],
         [-9.7831e+14,  6.1097e-43, -9.7840e+14,  6.1097e-43]]))

In [39]:
x.chunk(3, dim=0)

(tensor([[-9.7847e+14,  6.1097e-43, -9.7847e+14,  6.1097e-43],
         [-9.7846e+14,  6.1097e-43, -9.7846e+14,  6.1097e-43],
         [-9.7845e+14,  6.1097e-43, -9.7845e+14,  6.1097e-43],
         [-9.7845e+14,  6.1097e-43, -9.7844e+14,  6.1097e-43]]),
 tensor([[-9.7844e+14,  6.1097e-43, -9.7843e+14,  6.1097e-43],
         [-9.7843e+14,  6.1097e-43, -9.7842e+14,  6.1097e-43],
         [-9.7829e+14,  6.1097e-43, -9.7841e+14,  6.1097e-43],
         [-9.7819e+14,  6.1097e-43, -9.7835e+14,  6.1097e-43]]),
 tensor([[-9.7838e+14,  6.1097e-43, -9.7841e+14,  6.1097e-43],
         [-9.7831e+14,  6.1097e-43, -9.7840e+14,  6.1097e-43]]))

In [40]:
x = torch.FloatTensor([[[1, 2],
                        [3, 4]],
                        [[5, 6],
                         [7, 8]],
                         [[9, 10],
                          [11, 12]]])
indice = torch.LongTensor([2, 1])
x.shape

torch.Size([3, 2, 2])

In [44]:
x.index_select(index=indice, dim=0), x.index_select(index=torch.LongTensor([1, 0]), dim=1)

(tensor([[[ 9., 10.],
          [11., 12.]],
 
         [[ 5.,  6.],
          [ 7.,  8.]]]),
 tensor([[[ 3.,  4.],
          [ 1.,  2.]],
 
         [[ 7.,  8.],
          [ 5.,  6.]],
 
         [[11., 12.],
          [ 9., 10.]]]))

In [45]:
x = torch.FloatTensor([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
y = torch.FloatTensor([[10, 11, 12], [13, 14, 15], [16, 17, 18]])
x.shape, y.shape

(torch.Size([3, 3]), torch.Size([3, 3]))

In [47]:
torch.concat([x, y], dim=-1)

tensor([[ 1.,  2.,  3., 10., 11., 12.],
        [ 4.,  5.,  6., 13., 14., 15.],
        [ 7.,  8.,  9., 16., 17., 18.]])

In [48]:
torch.concat([x, y[0:2, :]], dim=0)

tensor([[ 1.,  2.,  3.],
        [ 4.,  5.,  6.],
        [ 7.,  8.,  9.],
        [10., 11., 12.],
        [13., 14., 15.]])

In [50]:
torch.stack([x, y]), torch.stack([x, y], dim=-1)

(tensor([[[ 1.,  2.,  3.],
          [ 4.,  5.,  6.],
          [ 7.,  8.,  9.]],
 
         [[10., 11., 12.],
          [13., 14., 15.],
          [16., 17., 18.]]]),
 tensor([[[ 1., 10.],
          [ 2., 11.],
          [ 3., 12.]],
 
         [[ 4., 13.],
          [ 5., 14.],
          [ 6., 15.]],
 
         [[ 7., 16.],
          [ 8., 17.],
          [ 9., 18.]]]))

In [51]:
a = torch.FloatTensor(np.array([[1, 2],
                                [3, 4]]))
a.reshape(2, 1, 2).expand(2, 3, 2)

tensor([[[1., 2.],
         [1., 2.],
         [1., 2.]],

        [[3., 4.],
         [3., 4.],
         [3., 4.]]])

In [52]:
a.reshape(2, 1, 2)

tensor([[[1., 2.]],

        [[3., 4.]]])

In [53]:
x = torch.randperm(10)
x

tensor([6, 9, 0, 2, 5, 3, 7, 1, 4, 8])

In [54]:
x = torch.randperm(3 ** 3).reshape(3, 3, -1)
x

tensor([[[12, 26,  7],
         [ 0, 10, 20],
         [ 6, 23,  1]],

        [[21, 19, 14],
         [ 9, 24, 18],
         [17, 15,  8]],

        [[ 4, 13, 11],
         [22,  5,  2],
         [25,  3, 16]]])

In [55]:
x.argmax(dim=0), x.argmax(dim=1), x.argmax(dim=-1)

(tensor([[1, 0, 1],
         [2, 1, 0],
         [2, 0, 2]]),
 tensor([[0, 0, 1],
         [0, 1, 1],
         [2, 0, 2]]),
 tensor([[1, 2, 1],
         [0, 1, 0],
         [1, 0, 0]]))

In [58]:
torch.sort(x, dim=0, descending=True)

torch.return_types.sort(
values=tensor([[[21, 26, 14],
         [22, 24, 20],
         [25, 23, 16]],

        [[12, 19, 11],
         [ 9, 10, 18],
         [17, 15,  8]],

        [[ 4, 13,  7],
         [ 0,  5,  2],
         [ 6,  3,  1]]]),
indices=tensor([[[1, 0, 1],
         [2, 1, 0],
         [2, 0, 2]],

        [[0, 1, 2],
         [1, 0, 1],
         [1, 1, 1]],

        [[2, 2, 0],
         [0, 2, 2],
         [0, 2, 0]]]))

In [59]:
torch.sort(x, dim=0, descending=True).values

tensor([[[21, 26, 14],
         [22, 24, 20],
         [25, 23, 16]],

        [[12, 19, 11],
         [ 9, 10, 18],
         [17, 15,  8]],

        [[ 4, 13,  7],
         [ 0,  5,  2],
         [ 6,  3,  1]]])

In [61]:
x, torch.sort(x, dim=1, descending=True).values

(tensor([[[12, 26,  7],
          [ 0, 10, 20],
          [ 6, 23,  1]],
 
         [[21, 19, 14],
          [ 9, 24, 18],
          [17, 15,  8]],
 
         [[ 4, 13, 11],
          [22,  5,  2],
          [25,  3, 16]]]),
 tensor([[[12, 26, 20],
          [ 6, 23,  7],
          [ 0, 10,  1]],
 
         [[21, 24, 18],
          [17, 19, 14],
          [ 9, 15,  8]],
 
         [[25, 13, 16],
          [22,  5, 11],
          [ 4,  3,  2]]]))

In [62]:
x = torch.FloatTensor([i for i in range(3 ** 2)]).reshape(3, -1)
mask = x > 4

In [64]:
x, mask

(tensor([[0., 1., 2.],
         [3., 4., 5.],
         [6., 7., 8.]]),
 tensor([[False, False, False],
         [False, False,  True],
         [ True,  True,  True]]))

In [65]:
x.masked_fill(mask, value=-1)

tensor([[ 0.,  1.,  2.],
        [ 3.,  4., -1.],
        [-1., -1., -1.]])

In [67]:
x = torch.ones(2, 3)
x

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [68]:
torch.zeros_like(x)

tensor([[0., 0., 0.],
        [0., 0., 0.]])