In [1]:
import torch
import torch.nn as nn
import numpy as np

In [2]:
x = torch.FloatTensor([i + 1 for i in range(6)]).reshape(3, -1)
y = torch.FloatTensor([1, 2]).expand(2, 2)
x, y

(tensor([[1., 2.],
         [3., 4.],
         [5., 6.]]),
 tensor([[1., 2.],
         [1., 2.]]))

In [3]:
torch.matmul(x, y)

tensor([[ 3.,  6.],
        [ 7., 14.],
        [11., 22.]])

In [4]:
x = torch.randperm(3 * 3 * 2).reshape(3, 3, 2)
y = torch.randperm(3 * 2 * 3).reshape(3, 2, 3)
x, y

(tensor([[[ 7,  6],
          [17, 12],
          [ 1, 14]],
 
         [[13, 16],
          [ 4, 11],
          [15,  3]],
 
         [[ 0,  2],
          [ 5,  8],
          [ 9, 10]]]),
 tensor([[[10, 16, 13],
          [ 6, 11,  8]],
 
         [[15,  2,  4],
          [ 9,  3,  1]],
 
         [[ 7, 14, 17],
          [ 5,  0, 12]]]))

In [5]:
torch.bmm(x, y)

tensor([[[106, 178, 139],
         [242, 404, 317],
         [ 94, 170, 125]],

        [[339,  74,  68],
         [159,  41,  27],
         [252,  39,  63]],

        [[ 10,   0,  24],
         [ 75,  70, 181],
         [113, 126, 273]]])

In [6]:
W = torch.FloatTensor([i + 1 for i in range(6)]).reshape(3, 2)
b = torch.FloatTensor([2, 2])

In [7]:
class MyLinear(nn.Module):
    def __init__(self, input_dim=3, output_dim=2):
        self.input_dim = input_dim
        self.output_dim = output_dim
        
        super().__init__()

        self.W = torch.FloatTensor(input_dim, output_dim)
        self.b = torch.FloatTensor(output_dim)

    def forward(self, X):
        y = torch.matmul(X, self.W) + self.b
        return y

In [11]:
x = torch.FloatTensor(4, 3)
linear = MyLinear(3, 2)
y = linear(x)
y

tensor([[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]])

In [12]:
class MyLinear(nn.Module):
    def __init__(self, input_dim=3, output_dim=2):
        self.input_dim = input_dim
        self.output_dim = output_dim
        
        super().__init__()

        self.W = nn.Parameter(torch.FloatTensor(input_dim, output_dim))
        self.b = nn.Parameter(torch.FloatTensor(output_dim))

    def forward(self, X):
        y = torch.matmul(X, self.W) + self.b
        return y

In [13]:
x = torch.FloatTensor(4, 3)
linear = MyLinear(3, 2)
y = linear(x)
y

tensor([[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]], grad_fn=<AddBackward0>)

In [15]:
for par in linear.parameters():
    print(par)

Parameter containing:
tensor([[0.0000e+00, 7.4269e-44],
        [1.8754e+28, 2.0592e+23],
        [2.5985e+20, 1.2868e-11]], requires_grad=True)
Parameter containing:
tensor([0., 0.], requires_grad=True)


In [16]:
linear = nn.Linear(3, 2)
y = linear(x)
y

tensor([[ 0.1480, -0.5495],
        [ 0.1480, -0.5495],
        [ 0.1480, -0.5495],
        [ 0.1480, -0.5495]], grad_fn=<AddmmBackward0>)

In [17]:
for par in linear.parameters():
    print(par)

Parameter containing:
tensor([[-0.1413,  0.3011,  0.2212],
        [ 0.5016, -0.4541, -0.2207]], requires_grad=True)
Parameter containing:
tensor([ 0.1480, -0.5495], requires_grad=True)


In [18]:
class MyLinear(nn.Module):
    def __init__(self, input_dim=3, output_dim=2):
        self.input_dim = input_dim
        self.output_dim = output_dim
        
        super().__init__()

        self.linear = nn.Linear(input_dim, output_dim)

    def forward(self, X):
        y = self.linear(X)
        return y

In [19]:
x = torch.FloatTensor(4, 3)
linear = MyLinear(3, 2)
y = linear(x)
y

tensor([[ 0.4700, -0.4022],
        [ 0.4700, -0.4022],
        [ 0.4700, -0.4022],
        [ 0.4700, -0.4022]], grad_fn=<AddmmBackward0>)

In [20]:
for par in linear.parameters():
    print(par)

Parameter containing:
tensor([[ 0.3514,  0.5467,  0.4748],
        [-0.1260,  0.0434, -0.1823]], requires_grad=True)
Parameter containing:
tensor([ 0.4700, -0.4022], requires_grad=True)
